package injection

import (
	"fmt"
	"strings"
)

// EmitOptions controls test-input rendering.
type EmitOptions struct {
	// PromptPath identifies the prompt under test (printed as a
	// comment header in the emitted file).
	PromptPath string

	// Language picks the output flavor: "python" (pytest), "typescript"
	// (vitest), or "json" (raw list, for ad-hoc tooling).
	Language string
}

// Emit renders the test inputs for one or more matched patterns as a
// runnable test file body. The returned string is dropped verbatim
// into a file the user can run; terrain does not write the file
// itself.
//
// The output is intentionally a test scaffold, not a runner. Users
// drop the file into their existing test directory and run it via
// pytest / vitest. When a prompt fixture exists (a recorded
// model response), the user wires the assertion in their test code;
// terrain does not need to host the model call.
func Emit(matches []Match, opts EmitOptions) string {
	switch opts.Language {
	case "typescript", "ts":
		return emitTypeScript(matches, opts)
	case "json":
		return emitJSON(matches, opts)
	default:
		return emitPython(matches, opts)
	}
}

func emitPython(matches []Match, opts EmitOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `terrain inject`. Drop into your tests/ tree.\n")
	if opts.PromptPath != "" {
		fmt.Fprintf(&b, "# Prompt under test: %s\n", opts.PromptPath)
	}
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# These inputs exercise %d injection pattern(s).\n", len(matches))
	fmt.Fprintf(&b, "# Replace `your_prompt_invoke(...)` with the real call into your\n")
	fmt.Fprintf(&b, "# prompt pipeline. Replace `expected_safe_behavior(...)` with the\n")
	fmt.Fprintf(&b, "# assertion that the output is NOT a successful injection.\n\n")
	fmt.Fprintf(&b, "import pytest\n\n")
	for _, m := range matches {
		funcName := strings.ReplaceAll(string(m.Pattern.ID), "-", "_")
		fmt.Fprintf(&b, "@pytest.mark.parametrize(\"injection_input\", [\n")
		for _, in := range m.Pattern.Inputs {
			fmt.Fprintf(&b, "    %s,\n", pyQuote(in))
		}
		fmt.Fprintf(&b, "])\n")
		fmt.Fprintf(&b, "def test_resists_%s(injection_input):\n", funcName)
		fmt.Fprintf(&b, "    # Pattern: %s — %s\n", m.Pattern.ID, m.Pattern.Title)
		fmt.Fprintf(&b, "    result = your_prompt_invoke(injection_input)\n")
		fmt.Fprintf(&b, "    assert expected_safe_behavior(result), \\\n")
		fmt.Fprintf(&b, "        f\"%%s leaked / jailbroken on input: {injection_input!r}\" %% %q\n\n", m.Pattern.ID)
	}
	return b.String()
}

func emitTypeScript(matches []Match, opts EmitOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by `terrain inject`. Drop into your tests/ tree.\n")
	if opts.PromptPath != "" {
		fmt.Fprintf(&b, "// Prompt under test: %s\n", opts.PromptPath)
	}
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// These inputs exercise %d injection pattern(s).\n", len(matches))
	fmt.Fprintf(&b, "// Replace `yourPromptInvoke(...)` with the real call into your\n")
	fmt.Fprintf(&b, "// prompt pipeline. Replace `expectedSafeBehavior(...)` with the\n")
	fmt.Fprintf(&b, "// assertion that the output is NOT a successful injection.\n\n")
	fmt.Fprintf(&b, "import { describe, it, expect } from 'vitest';\n\n")
	for _, m := range matches {
		fmt.Fprintf(&b, "describe('resists %s — %s', () => {\n", m.Pattern.ID, m.Pattern.Title)
		fmt.Fprintf(&b, "  const inputs = [\n")
		for _, in := range m.Pattern.Inputs {
			fmt.Fprintf(&b, "    %s,\n", tsQuote(in))
		}
		fmt.Fprintf(&b, "  ];\n")
		fmt.Fprintf(&b, "  it.each(inputs)('rejects: %%s', async (input) => {\n")
		fmt.Fprintf(&b, "    const result = await yourPromptInvoke(input);\n")
		fmt.Fprintf(&b, "    expect(expectedSafeBehavior(result)).toBe(true);\n")
		fmt.Fprintf(&b, "  });\n")
		fmt.Fprintf(&b, "});\n\n")
	}
	return b.String()
}

func emitJSON(matches []Match, _ EmitOptions) string {
	var b strings.Builder
	b.WriteString("{\n  \"patterns\": [\n")
	for i, m := range matches {
		b.WriteString("    {\n")
		fmt.Fprintf(&b, "      \"id\": %q,\n", string(m.Pattern.ID))
		fmt.Fprintf(&b, "      \"title\": %q,\n", m.Pattern.Title)
		fmt.Fprintf(&b, "      \"marker\": %q,\n", m.Marker)
		b.WriteString("      \"inputs\": [\n")
		for j, in := range m.Pattern.Inputs {
			fmt.Fprintf(&b, "        %s", jsonQuote(in))
			if j < len(m.Pattern.Inputs)-1 {
				b.WriteString(",")
			}
			b.WriteString("\n")
		}
		b.WriteString("      ]\n    }")
		if i < len(matches)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString("  ]\n}\n")
	return b.String()
}

// pyQuote wraps s in a triple-double-quoted Python string, escaping
// `"""` sequences.
func pyQuote(s string) string {
	s = strings.ReplaceAll(s, `"""`, `\"\"\"`)
	return `"""` + s + `"""`
}

// tsQuote wraps s in a TypeScript backtick template literal,
// escaping backticks and `${`.
func tsQuote(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "`", "\\`")
	s = strings.ReplaceAll(s, "${", "\\${")
	return "`" + s + "`"
}

// jsonQuote produces a JSON-encoded string literal.
func jsonQuote(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	return `"` + s + `"`
}
