// Package fixscaffold generates concrete remediation snippets that
// developers can drop into their repo to close a finding.
//
// The verdict-quality review (2026-05-15) identified fix scaffolds as
// the single highest lever for per-PR act-on rate — Dependabot's
// "upgrade to version X" is itself a fix scaffold; Terrain's
// semantic equivalent is "here's a Promptfoo eval YAML that covers
// this prompt." Scaffolds don't need to be auto-applied; just having
// them inline triples remediation rates (CodeQL's empirical baseline).
//
// One generator per rule + language is the right grain. Each generator
// returns the scaffold body plus a target path hint ("evals/X.yaml").
// The PR-comment renderer is responsible for actually attaching the
// scaffold to the comment.
package fixscaffold

import (
	"fmt"
	"path/filepath"
	"strings"
)

// Scaffold is a generated remediation snippet.
type Scaffold struct {
	// RuleID is the finding's rule.
	RuleID string

	// Language is the target language tag (`yaml`, `python`, `typescript`).
	Language string

	// TargetPath is the suggested filename for the scaffold (relative
	// to repo root). Caller may override.
	TargetPath string

	// Body is the scaffold contents.
	Body string

	// Description is one-line user-facing text shown in the PR comment.
	Description string
}

// Generator produces a Scaffold given the finding context.
type Generator interface {
	// RuleID is the rule this generator handles.
	RuleID() string

	// Generate returns a Scaffold for the given context. surfacePath
	// is the path of the AI surface that triggered the finding. lang
	// is the surrounding repo's primary language. Returns nil when the
	// generator decides no scaffold is appropriate.
	Generate(surfacePath, lang string) *Scaffold
}

// Registry holds the active generators keyed by rule ID.
type Registry struct {
	gens map[string]Generator
}

// NewRegistry returns a registry populated with the default generators
// shipped in this package.
func NewRegistry() *Registry {
	r := &Registry{gens: map[string]Generator{}}
	r.Register(&PromptFooEvalGenerator{})
	r.Register(&DeepEvalGenerator{})
	r.Register(&MetricTrackerGenerator{})
	return r
}

// Register adds a generator to the registry. Last registration wins
// for a given rule ID.
func (r *Registry) Register(g Generator) {
	r.gens[g.RuleID()] = g
}

// Generate returns a Scaffold for the given rule, or nil when no
// generator is registered for the rule.
func (r *Registry) Generate(ruleID, surfacePath, lang string) *Scaffold {
	if g, ok := r.gens[ruleID]; ok {
		return g.Generate(surfacePath, lang)
	}
	return nil
}

// ── PromptFoo eval scaffold ─────────────────────────────────────────

// PromptFooEvalGenerator emits a Promptfoo YAML eval scaffold for the
// `ai.surface.missing_eval` and `ai.prompt_file_missing_eval` rules.
type PromptFooEvalGenerator struct{}

// RuleID returns the canonical rule ID this generator handles.
// The registry indexes generators by rule ID, but we also accept
// the prompt-file variant via a separate registration if desired.
func (g *PromptFooEvalGenerator) RuleID() string {
	return "ai.surface.missing_eval"
}

// Generate produces a Promptfoo YAML scaffold tailored to the surface
// path. Works for any language since Promptfoo configs are YAML.
func (g *PromptFooEvalGenerator) Generate(surfacePath, _ string) *Scaffold {
	base := strings.TrimSuffix(filepath.Base(surfacePath), filepath.Ext(surfacePath))
	if base == "" {
		base = "untitled"
	}
	targetPath := fmt.Sprintf("evals/promptfoo/%s.yaml", base)
	body := fmt.Sprintf(`# Generated by Terrain for the AI surface at:
#   %s
#
# Replace the placeholder prompt / assertions with the ones your
# surface actually emits. The defaults below are starting points;
# Terrain will reload this file as evidence of coverage once it
# references the surface path.

description: "Eval coverage for %s"

prompts:
  - file://%s

providers:
  # Configure at least one provider. The OPENAI_API_KEY env var
  # is the simplest path; swap in Anthropic / Gemini / etc. as
  # appropriate.
  - openai:chat:gpt-4o-mini

tests:
  - description: "smoke — minimal happy-path input"
    vars:
      query: "Hello, world"
    assert:
      - type: not-empty
      - type: contains-any
        value: ["hi", "hello"]

  - description: "regression — known-failure input"
    vars:
      query: "TODO: replace with a real adversarial or edge-case input"
    assert:
      - type: not-empty
      # Promptfoo supports llm-rubric for semantic checks:
      # https://promptfoo.dev/docs/configuration/expected-outputs/llm-rubric/
      - type: llm-rubric
        value: "The answer is grounded in the prompt context and does not hallucinate."
`, surfacePath, base, surfacePath)
	return &Scaffold{
		RuleID:      "ai.surface.missing_eval",
		Language:    "yaml",
		TargetPath:  targetPath,
		Body:        body,
		Description: fmt.Sprintf("Create %s with at least one smoke test and one regression case", targetPath),
	}
}

// ── DeepEval scaffold ───────────────────────────────────────────────

// DeepEvalGenerator emits a DeepEval Python test scaffold. Useful for
// teams that prefer pytest-shaped evals over Promptfoo's YAML.
type DeepEvalGenerator struct{}

// RuleID — registered as an alternate for the same rule. Callers can
// pick which scaffold matches the team's preferred eval framework.
func (g *DeepEvalGenerator) RuleID() string {
	return "ai.surface.missing_eval.deepeval"
}

// Generate emits a deepeval pytest scaffold targeted at the surface.
func (g *DeepEvalGenerator) Generate(surfacePath, _ string) *Scaffold {
	base := strings.TrimSuffix(filepath.Base(surfacePath), filepath.Ext(surfacePath))
	if base == "" {
		base = "untitled"
	}
	targetPath := fmt.Sprintf("tests/evals/test_%s_deepeval.py", base)
	body := fmt.Sprintf(`# Generated by Terrain for the AI surface at:
#   %s
#
# This uses DeepEval (pytest-style). The fixture should invoke the
# surface and return an LLMTestCase; the metrics are starting points.

import pytest
from deepeval import assert_test
from deepeval.metrics import AnswerRelevancyMetric, FaithfulnessMetric
from deepeval.test_case import LLMTestCase


@pytest.fixture
def smoke_case():
    # TODO: replace with a real invocation of the surface at %s
    return LLMTestCase(
        input="Hello, world",
        actual_output="TODO: invoke surface and capture output",
        retrieval_context=[],
    )


def test_surface_relevance(smoke_case):
    metric = AnswerRelevancyMetric(threshold=0.7)
    assert_test(smoke_case, [metric])


def test_surface_faithfulness(smoke_case):
    metric = FaithfulnessMetric(threshold=0.7)
    assert_test(smoke_case, [metric])
`, surfacePath, surfacePath)
	return &Scaffold{
		RuleID:      "ai.surface.missing_eval.deepeval",
		Language:    "python",
		TargetPath:  targetPath,
		Body:        body,
		Description: fmt.Sprintf("Create %s with DeepEval relevance + faithfulness assertions", targetPath),
	}
}

// ── Metric-tracker scaffold ─────────────────────────────────────────

// MetricTrackerGenerator emits an mlflow-or-wandb init scaffold for
// the `ai.train.missing_tracker` rule. Returns the scaffold most
// appropriate to the language tag.
type MetricTrackerGenerator struct{}

// RuleID — the rule this generator handles.
func (g *MetricTrackerGenerator) RuleID() string {
	return "ai.train.missing_tracker"
}

// Generate emits a tracker-init snippet tailored to language. Python
// gets mlflow; other languages get a generic comment block guiding
// the user to the right tracker.
func (g *MetricTrackerGenerator) Generate(surfacePath, lang string) *Scaffold {
	switch strings.ToLower(lang) {
	case "python":
		return g.python(surfacePath)
	case "javascript", "typescript", "node":
		return g.node(surfacePath)
	default:
		return g.generic(surfacePath, lang)
	}
}

func (g *MetricTrackerGenerator) python(surfacePath string) *Scaffold {
	body := fmt.Sprintf(`# Insert near the top of %s to enable experiment tracking:
import mlflow

mlflow.set_experiment("default")  # TODO: name your experiment

with mlflow.start_run():
    mlflow.log_param("model", "TODO")           # hyperparameters
    mlflow.log_param("seed", 0)
    # ... existing training loop ...
    mlflow.log_metric("loss", float(loss))      # per-step or per-epoch
    mlflow.log_metric("val_acc", float(val_acc))
    mlflow.log_artifact("model.pt")             # final artifact
`, surfacePath)
	return &Scaffold{
		RuleID:      "ai.train.missing_tracker",
		Language:    "python",
		TargetPath:  surfacePath,
		Body:        body,
		Description: "Wrap the training loop in an mlflow.start_run() context",
	}
}

func (g *MetricTrackerGenerator) node(surfacePath string) *Scaffold {
	body := fmt.Sprintf(`// Insert near the top of %s to enable experiment tracking:
import wandb from '@wandb/sdk';

await wandb.init({
  project: 'default',  // TODO: name your project
  config: {
    model: 'TODO',
    seed: 0,
  },
});

// ... existing training loop ...
await wandb.log({ loss, val_acc, step });
await wandb.finish();
`, surfacePath)
	return &Scaffold{
		RuleID:      "ai.train.missing_tracker",
		Language:    "typescript",
		TargetPath:  surfacePath,
		Body:        body,
		Description: "Wrap the training loop in wandb.init / wandb.log calls",
	}
}

func (g *MetricTrackerGenerator) generic(surfacePath, lang string) *Scaffold {
	body := fmt.Sprintf(`/*
 * Terrain detected training in %s with no metric-tracking calls.
 *
 * The %s ecosystem doesn't have a single canonical tracker, but
 * common patterns include:
 *
 *   - mlflow (cross-language via REST: https://mlflow.org/docs/latest/tracking.html#mlflow-tracking-server)
 *   - weights & biases (REST + per-language SDKs)
 *   - cloud-platform-managed tracking (SageMaker / Vertex AI / Azure ML / Databricks)
 *
 * Pick a tracker, initialize it before the training loop, and log
 * per-step or per-epoch metrics. Terrain will stop flagging this
 * file once a tracker call is detected anywhere in the repo.
 */
`, surfacePath, lang)
	return &Scaffold{
		RuleID:      "ai.train.missing_tracker",
		Language:    "text",
		TargetPath:  surfacePath,
		Body:        body,
		Description: "Pick a metric tracker and wire it into the training loop",
	}
}
