package main

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/pmclSF/terrain/internal/aidetect"
	"github.com/pmclSF/terrain/internal/analysis"
	"github.com/pmclSF/terrain/internal/models"
)

// runDescribeCommand implements `terrain describe` — the first-run UX
// per PRODUCT.md §16. Inspects the repo, lists detected AI/ML surfaces,
// and either prints them or writes a starter terrain.yaml.
//
// Security-friendly defaults per the task brief:
//   - No network calls (everything inferred from source structure)
//   - No write without --write flag and overwrite confirmation
//   - terrain.yaml.example written when terrain.yaml already exists
func runDescribeCommand(root string, write bool) error {
	abs, err := filepath.Abs(root)
	if err != nil {
		return err
	}

	fmt.Printf("Terrain — describing %s\n\n", abs)

	det := aidetect.Detect(abs)

	// Detect AI surfaces via the existing inference (Tier 1).
	var sourceFiles []string
	_ = filepath.Walk(abs, func(path string, info os.FileInfo, walkErr error) error {
		if walkErr != nil {
			return nil
		}
		if info.IsDir() {
			if shouldSkipForDescribe(filepath.Base(path)) {
				return filepath.SkipDir
			}
			return nil
		}
		ext := strings.ToLower(filepath.Ext(path))
		if !isDescribeSourceExt(ext) {
			return nil
		}
		rel, _ := filepath.Rel(abs, path)
		sourceFiles = append(sourceFiles, rel)
		return nil
	})

	extraSurfaces := analysis.DetectExtraAISurfaces(abs, nil, nil, sourceFiles)

	// Summarize detected frameworks.
	fmt.Println("Frameworks detected:")
	if len(det.Frameworks) == 0 {
		fmt.Println("  (none — repo doesn't appear to use AI/ML libraries)")
	} else {
		seen := map[string]bool{}
		for _, fw := range det.Frameworks {
			if seen[fw.Name] {
				continue
			}
			seen[fw.Name] = true
			fmt.Printf("  - %s (via %s)\n", fw.Name, fw.Source)
		}
	}
	fmt.Println()

	// Summarize surfaces.
	fmt.Printf("AI / ML surfaces (%d):\n", len(extraSurfaces))
	byKind := map[models.CodeSurfaceKind][]models.CodeSurface{}
	for _, s := range extraSurfaces {
		byKind[s.Kind] = append(byKind[s.Kind], s)
	}
	kinds := make([]models.CodeSurfaceKind, 0, len(byKind))
	for k := range byKind {
		kinds = append(kinds, k)
	}
	sort.Slice(kinds, func(i, j int) bool { return kinds[i] < kinds[j] })
	for _, k := range kinds {
		fmt.Printf("  %s:\n", k)
		for _, s := range byKind[k] {
			fmt.Printf("    %s — %s\n", s.Name, s.Path)
		}
	}
	fmt.Println()

	if !write {
		fmt.Println("To generate a starter terrain.yaml, re-run with --write.")
		return nil
	}

	return writeDescribeYAML(abs, det, extraSurfaces)
}

// writeDescribeYAML composes a starter terrain.yaml from the
// detected frameworks and surfaces.
func writeDescribeYAML(root string, det *aidetect.DetectResult, surfaces []models.CodeSurface) error {
	targetPath := filepath.Join(root, "terrain.yaml")
	if _, err := os.Stat(targetPath); err == nil {
		fmt.Printf("%s already exists.\n", targetPath)
		fmt.Print("Overwrite? [y/N]: ")
		reader := bufio.NewReader(os.Stdin)
		line, _ := reader.ReadString('\n')
		line = strings.TrimSpace(strings.ToLower(line))
		if line != "y" && line != "yes" {
			alt := filepath.Join(root, "terrain.yaml.example")
			fmt.Printf("Writing to %s instead.\n", alt)
			targetPath = alt
		}
	}

	var b strings.Builder
	b.WriteString("# terrain.yaml — generated by `terrain describe`.\n")
	b.WriteString("# Schema v1 (https://terrain.dev/schemas/terrain.yaml.v1.json).\n\n")
	b.WriteString("version: 1\n\n")

	primaryFw := primaryEvalFramework(det)
	if primaryFw != "" {
		b.WriteString("ai:\n")
		b.WriteString("  framework: " + primaryFw + "\n")
		b.WriteString("  scenarios_dir: evals/\n")
		b.WriteString("  baselines_dir: .terrain/baselines/\n\n")
	}

	if len(surfaces) > 0 {
		b.WriteString("surfaces:\n")
		for _, s := range surfaces {
			key := slugifyForYAML(s.Name)
			surfaceType := surfaceKindToYAMLType(s.Kind)
			b.WriteString("  " + key + ":\n")
			b.WriteString("    description: \"" + escapeForYAML(s.Name) + "\"\n")
			b.WriteString("    type: " + surfaceType + "\n")
			b.WriteString("    file_path: " + s.Path + "\n")
		}
		b.WriteString("\n")
	}

	if err := os.WriteFile(targetPath, []byte(b.String()), 0o644); err != nil {
		return err
	}
	fmt.Printf("Wrote %s\n", targetPath)
	fmt.Println("Review and commit. Edit `surfaces:` to add descriptions / model identifiers.")
	return nil
}

func primaryEvalFramework(det *aidetect.DetectResult) string {
	want := map[string]bool{
		"promptfoo": true, "deepeval": true, "ragas": true,
		"great-expectations": true,
	}
	for _, fw := range det.Frameworks {
		if want[fw.Name] {
			return fw.Name
		}
	}
	return ""
}

func surfaceKindToYAMLType(k models.CodeSurfaceKind) string {
	switch k {
	case models.SurfacePrompt, models.SurfaceAgent:
		return "llm"
	case models.SurfaceRetrieval:
		return "rag_pipeline"
	case models.SurfaceDataset:
		return "feature_pipeline"
	case models.SurfaceModel:
		return "classical_ml"
	}
	return "llm"
}

func slugifyForYAML(name string) string {
	var b strings.Builder
	prevUnderscore := false
	for _, r := range strings.ToLower(name) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			b.WriteRune(r)
			prevUnderscore = false
		case !prevUnderscore && b.Len() > 0:
			b.WriteRune('_')
			prevUnderscore = true
		}
	}
	out := strings.TrimRight(b.String(), "_")
	if out == "" || (out[0] >= '0' && out[0] <= '9') {
		out = "surface_" + out
	}
	return out
}

func escapeForYAML(s string) string {
	return strings.ReplaceAll(s, `"`, `\"`)
}

func isDescribeSourceExt(ext string) bool {
	switch ext {
	case ".py", ".js", ".ts", ".tsx", ".jsx", ".mjs", ".go", ".java", ".rb", ".rs":
		return true
	}
	return false
}

func shouldSkipForDescribe(name string) bool {
	switch name {
	case ".git", "node_modules", "vendor", ".venv", "venv", "dist", "build", ".terrain":
		return true
	}
	return false
}
