package engine

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestRunInit_CreatesTerrainDir(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	// Create a minimal repo structure.
	writeArtifact(t, root, "src/app.ts", "export function hello() {}")
	writeArtifact(t, root, "test/app.test.ts", "describe('app', () => { it('works', () => {}); });")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	// .terrain/ directory should be created.
	terrainDir := filepath.Join(root, ".terrain")
	info, err := os.Stat(terrainDir)
	if err != nil {
		t.Fatalf(".terrain/ directory not created: %v", err)
	}
	if !info.IsDir() {
		t.Error(".terrain should be a directory")
	}

	// Policy file should be created.
	if result.PolicyPath == "" {
		t.Error("expected PolicyPath to be set")
	}
	if _, err := os.Stat(result.PolicyPath); err != nil {
		t.Errorf("policy file not created at %s: %v", result.PolicyPath, err)
	}
}

func TestRunInit_GeneratesPolicyYAML(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "src/app.go", "package main\nfunc main() {}")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	data, err := os.ReadFile(result.PolicyPath)
	if err != nil {
		t.Fatalf("read policy: %v", err)
	}

	content := string(data)
	// Should contain commented-out rules.
	if !strings.Contains(content, "# disallow_skipped_tests") {
		t.Error("policy should contain commented disallow_skipped_tests rule")
	}
	if !strings.Contains(content, "# minimum_coverage_percent") {
		t.Error("policy should contain commented minimum_coverage_percent rule")
	}
	// Should not have any uncommented rules.
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") || trimmed == "rules:" {
			continue
		}
		t.Errorf("unexpected uncommented line in policy: %q", trimmed)
	}
}

func TestRunInit_GeneratesTerrainYAML(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "test/app.test.ts", "it('works', () => {});")
	writeArtifact(t, root, "package.json", `{"devDependencies":{"jest":"^29.0.0"}}`)

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	if result.ConfigPath == "" {
		t.Fatal("expected ConfigPath to be set")
	}

	data, err := os.ReadFile(result.ConfigPath)
	if err != nil {
		t.Fatalf("read config: %v", err)
	}

	content := string(data)
	if !strings.Contains(content, "# Generated by: terrain init") {
		t.Error("config should contain generation comment")
	}
	if !strings.Contains(content, "# manual_coverage:") {
		t.Error("config should contain manual_coverage template")
	}
	if !strings.Contains(content, "# scenarios:") {
		t.Error("config should contain scenarios template")
	}
}

func TestRunInit_DetectsFrameworks(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "package.json", `{"devDependencies":{"jest":"^29.0.0","vitest":"^1.0.0"}}`)
	writeArtifact(t, root, "test/a.test.ts", "it('works', () => {});")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	if len(result.Frameworks) == 0 {
		t.Error("expected at least 1 framework detected")
	}

	names := map[string]bool{}
	for _, fw := range result.Frameworks {
		names[fw.Name] = true
	}
	if !names["jest"] {
		t.Error("expected jest to be detected")
	}
}

func TestRunInit_DetectsArtifacts(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "coverage/lcov.info", "TN:\nSF:src/a.ts\nend_of_record\n")
	writeArtifact(t, root, "junit.xml", `<?xml version="1.0"?><testsuites/>`)
	writeArtifact(t, root, "test/a.test.ts", "it('works', () => {});")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	if result.Artifacts.CoveragePath == "" {
		t.Error("expected coverage to be detected")
	}
	if len(result.Artifacts.RuntimePaths) == 0 {
		t.Error("expected runtime to be detected")
	}

	// Config should mention detected artifacts.
	if result.ConfigPath != "" {
		data, _ := os.ReadFile(result.ConfigPath)
		if !strings.Contains(string(data), "Detected coverage") {
			t.Error("config should mention detected coverage in comments")
		}
	}
}

func TestRunInit_CountsTestFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "test/a.test.ts", "it('a', () => {});")
	writeArtifact(t, root, "test/b.test.ts", "it('b', () => {});")
	writeArtifact(t, root, "test/c.spec.ts", "it('c', () => {});")
	writeArtifact(t, root, "internal/pkg/foo_test.go", "func TestFoo(t *testing.T) {}")
	writeArtifact(t, root, "tests/test_bar.py", "def test_bar(): pass")
	writeArtifact(t, root, "src/app.ts", "export function hello() {}")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	if result.TestFileCount != 5 {
		t.Errorf("expected 5 test files, got %d", result.TestFileCount)
	}
}

func TestRunInit_SkipsExistingConfig(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, ".terrain/policy.yaml", "rules:\n  # existing\n")
	writeArtifact(t, root, ".terrain/terrain.yaml", "# existing config\n")
	writeArtifact(t, root, "test/a.test.ts", "it('works', () => {});")

	result, err := RunInit(root)
	if err != nil {
		t.Fatalf("RunInit failed: %v", err)
	}

	// Should not overwrite existing files.
	if result.PolicyPath != "" {
		t.Error("should not generate policy.yaml when it already exists")
	}
	if result.ConfigPath != "" {
		t.Error("should not generate terrain.yaml when it already exists")
	}
	if !result.HasPolicyFile {
		t.Error("HasPolicyFile should be true")
	}
	if !result.HasTerrainYAML {
		t.Error("HasTerrainYAML should be true")
	}

	// Verify existing files are unchanged.
	data, _ := os.ReadFile(filepath.Join(root, ".terrain", "policy.yaml"))
	if string(data) != "rules:\n  # existing\n" {
		t.Error("existing policy.yaml should not be modified")
	}
}

func TestRunInit_InvalidRoot(t *testing.T) {
	t.Parallel()
	_, err := RunInit("/nonexistent/path/12345")
	if err == nil {
		t.Error("expected error for nonexistent root")
	}
}

func TestRunInit_Deterministic(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "test/a.test.ts", "it('works', () => {});")
	writeArtifact(t, root, "coverage/lcov.info", "TN:\nend_of_record\n")

	r1, err := RunInit(root)
	if err != nil {
		t.Fatalf("first run: %v", err)
	}

	// Delete generated files, run again.
	os.Remove(r1.PolicyPath)
	os.Remove(r1.ConfigPath)

	r2, err := RunInit(root)
	if err != nil {
		t.Fatalf("second run: %v", err)
	}

	// Generated config should be identical.
	d1, _ := os.ReadFile(r2.PolicyPath)
	d2, _ := os.ReadFile(r2.PolicyPath)
	if string(d1) != string(d2) {
		t.Error("policy.yaml should be deterministic")
	}

	if r1.TestFileCount != r2.TestFileCount {
		t.Errorf("test file count not deterministic: %d vs %d", r1.TestFileCount, r2.TestFileCount)
	}
}

func TestCountTestFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	writeArtifact(t, root, "a.test.ts", "x")
	writeArtifact(t, root, "b.spec.js", "x")
	writeArtifact(t, root, "c_test.go", "x")
	writeArtifact(t, root, "test_d.py", "x")
	writeArtifact(t, root, "ETest.java", "x")
	writeArtifact(t, root, "not_a_test.ts", "x")
	writeArtifact(t, root, "node_modules/x.test.ts", "x") // should be skipped

	count := countTestFiles(root)
	if count != 5 {
		t.Errorf("expected 5 test files, got %d", count)
	}
}

func TestIsTestFileName(t *testing.T) {
	t.Parallel()
	cases := []struct {
		name string
		want bool
	}{
		{"app.test.ts", true},
		{"app.spec.js", true},
		{"app_test.go", true},
		{"test_app.py", true},
		{"app_test.py", true},
		{"AppTest.java", true},
		{"app.ts", false},
		{"README.md", false},
	}
	for _, tc := range cases {
		if got := isTestFileName(tc.name); got != tc.want {
			t.Errorf("isTestFileName(%q) = %v, want %v", tc.name, got, tc.want)
		}
	}
}
