package changescope

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/pmclSF/terrain/internal/uitokens"
)

// RenderPRSummaryMarkdown writes a PR-ready markdown summary optimized
// for human review and merge decisions.
//
// 0.2 layout — designed for visual scanability on GitHub:
//
//   ## Terrain — <verdict>
//
//   > <one-sentence why> (blockquote callout)
//
//   | Metric | Value |
//   | ... compact 2-column table ... |
//
//   --- (horizontal rule between major sections)
//
//   ### Coverage gaps in changed code
//
//   - **`path/to/file.ts`** [HIGH] — <plain-language description>
//
//   ---
//
//   ### Recommended tests
//
//   ---
//
//   ### AI Risk Review
//
//   ---
//
//   <sub>Owners · Generated by Terrain · ...</sub>  (small footer)
//
// Each section is gated on having content, so tiny PRs stay tiny. The
// horizontal rules (`---`) give the comment visual rhythm — every
// section is a discrete card rather than a blob.
func RenderPRSummaryMarkdown(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	hr := func() {
		line("---")
		line("")
	}

	// Deduplicate findings at render time (safeguard).
	findings := DeduplicateFindings(pr.NewFindings)
	directRisk, indirectRisk, existingDebt := ClassifyFindingsDetailed(findings)

	// Merge recommendation.
	mergeRec, mergeExpl := MergeRecommendation(pr.PostureBand, findings)

	// --- Header — H2 verdict + blockquote subtitle. ---
	// Blockquote is more visually distinct than the previous italic line
	// and renders as a colored callout on GitHub.
	badge := postureBadge(pr.PostureBand)
	line("## %s Terrain — %s", badge, mergeRec)
	line("")
	if mergeExpl != "" {
		line("> %s", mergeExpl)
		line("")
	}

	// --- Compact metrics table ---
	// Bold labels in the left column for visual hierarchy. The middle-
	// dot separator (·) replaces commas in compound stats so the cell
	// content reads cleanly.
	line("| Metric | Value |")
	line("|---|---|")
	line("| **Changed files** | %d (%d source · %d test) |", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	if pr.ImpactedUnitCount > 0 {
		line("| **Impacted units** | %d |", pr.ImpactedUnitCount)
	}
	if pr.ProtectionGapCount > 0 {
		line("| **Protection gaps** | %d |", pr.ProtectionGapCount)
	}
	if len(pr.RecommendedTests) > 0 {
		if pr.TotalTestCount > 0 {
			line("| **Tests selected** | %d of %d (%s of suite) |",
				len(pr.RecommendedTests), pr.TotalTestCount,
				formatSuitePercent(len(pr.RecommendedTests), pr.TotalTestCount))
		} else {
			line("| **Tests selected** | %d |", len(pr.RecommendedTests))
		}
	}
	line("")

	// --- New risks introduced by this PR (directly changed files) ---
	if len(directRisk) > 0 {
		hr()
		line("### Coverage gaps in changed code")
		line("")
		renderFindingsCards(line, directRisk, 10)
	}

	// --- Indirectly impacted gaps (collapsed) ---
	if len(indirectRisk) > 0 {
		line("<details><summary><b>%d indirectly impacted protection %s</b></summary>", len(indirectRisk), pluralize(len(indirectRisk), "gap", "gaps"))
		line("")
		renderFindingsCards(line, indirectRisk, 5)
		line("</details>")
		line("")
	}

	// --- Pre-existing gaps touched by this change ---
	if len(existingDebt) > 0 {
		if len(existingDebt) <= 3 {
			hr()
			line("### Pre-existing issues (%d)", len(existingDebt))
			line("")
			for _, f := range existingDebt {
				renderFindingCard(line, f)
			}
		} else {
			line("<details><summary><b>%d pre-existing %s on changed files</b></summary>", len(existingDebt), pluralize(len(existingDebt), "issue", "issues"))
			line("")
			limit := 5
			if len(existingDebt) < limit {
				limit = len(existingDebt)
			}
			for _, f := range existingDebt[:limit] {
				renderFindingCard(line, f)
			}
			if len(existingDebt) > limit {
				line("- _...and %d more_", len(existingDebt)-limit)
				line("")
			}
			line("</details>")
			line("")
		}
	}

	// --- Test recommendations ---
	if len(pr.TestSelections) > 0 || len(pr.RecommendedTests) > 0 {
		hr()
		renderTestRecommendations(line, pr)
	}

	// --- AI Risk Review ---
	if pr.AI != nil {
		hr()
		renderAISection(line, pr)
	}

	// --- Footer (owners + limitations + branding) ---
	// Combined into a single small-text footer so individual elements
	// don't compete for attention with the main content.
	hr()
	footerParts := []string{}
	if len(pr.AffectedOwners) > 0 {
		footerParts = append(footerParts, fmt.Sprintf("**Owners:** %s", strings.Join(pr.AffectedOwners, ", ")))
	}
	if len(footerParts) > 0 {
		line("%s", strings.Join(footerParts, " · "))
		line("")
	}
	if len(pr.Limitations) > 0 {
		line("<details><summary><b>Limitations</b></summary>")
		line("")
		for _, l := range pr.Limitations {
			line("- %s", l)
		}
		line("")
		line("</details>")
		line("")
	}
	line("<sub>Generated by [Terrain](https://github.com/pmclSF/terrain) · `terrain pr --json` for machine-readable output</sub>")
}

// renderFindingsCards renders up to limit findings using the parallel
// "card" shape — file path first in code-format, severity badge in
// line, dash separator, plain description, and an optional action
// arrow. Matches the AI Risk Review render so the whole comment has a
// consistent visual rhythm. Trails a blank line so the next section
// header has breathing room.
func renderFindingsCards(line func(string, ...any), findings []ChangeScopedFinding, limit int) {
	if len(findings) < limit {
		limit = len(findings)
	}
	for _, f := range findings[:limit] {
		renderFindingCard(line, f)
	}
	if len(findings) > limit {
		overflow := SummarizeFindingsBySeverity(findings[limit:])
		parts := formatSeverityCounts(overflow)
		line("- _...and %d more (%s)_", len(findings)-limit, strings.Join(parts, ", "))
	}
	line("") // visual breathing room before the next section
}

// renderFindingCard emits one finding as a card-style bullet:
//
//	- **`path/to/file.go`** [HIGH] — <explanation>
//	  → <suggested action>
//
// Suggested action is omitted when the finding doesn't carry one.
func renderFindingCard(line func(string, ...any), f ChangeScopedFinding) {
	badge := severityIcon(f.Severity)
	line("- **`%s`** %s — %s", f.Path, badge, f.Explanation)
	if f.SuggestedAction != "" {
		line("  → %s", f.SuggestedAction)
	}
}

// pluralize returns "finding" or "findings" based on count. Used to
// avoid the awkward "finding(s)" notation in user-visible headers.
func pluralize(n int, singular, plural string) string {
	if n == 1 {
		return singular
	}
	return plural
}

// renderTestRecommendations renders the test recommendations section.
func renderTestRecommendations(line func(string, ...any), pr *PRAnalysis) {
	if len(pr.TestSelections) > 0 {
		line("### Recommended tests")
		line("")
		if pr.SelectionExplanation != "" {
			line("*%s*", pr.SelectionExplanation)
			line("")
		}

		if len(pr.TestSelections) <= 15 {
			reasons := formatTestReasons(pr.TestSelections)
			line("| Test | Confidence | Why |")
			line("|------|------------|-----|")
			for _, t := range pr.TestSelections {
				line("| `%s` | %s | %s |", t.Path, t.Confidence, reasons[t.Path])
			}
		} else {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			groups := GroupTestsByPackage(paths)
			line("| Package | Tests | Sample |")
			line("|---------|-------|--------|")
			for _, g := range groups {
				sample := g.Files[0]
				if len(g.Files) > 1 {
					sample += " ..."
				}
				line("| `%s` | %d | `%s` |", g.Package, g.Count, sample)
			}
		}
		line("")
	} else if len(pr.RecommendedTests) > 0 {
		line("### Recommended tests")
		line("")
		if len(pr.RecommendedTests) <= 15 {
			for _, t := range pr.RecommendedTests {
				line("- `%s`", t)
			}
		} else {
			groups := GroupTestsByPackage(pr.RecommendedTests)
			for _, g := range groups {
				line("- `%s/` — %d %s", g.Package, g.Count, pluralize(g.Count, "test", "tests"))
			}
		}
		line("")
	}
}

// RenderPRCommentConcise writes a concise one-line PR comment.
func RenderPRCommentConcise(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	findings := DeduplicateFindings(pr.NewFindings)
	mergeRec, _ := MergeRecommendation(pr.PostureBand, findings)
	badge := postureBadge(pr.PostureBand)
	line("%s **Terrain:** %s — %s", badge, mergeRec, pr.Summary)

	highCount := 0
	for _, f := range findings {
		if f.Severity == "high" {
			highCount++
		}
	}
	if highCount > 0 {
		line("  - %d high-severity finding(s) require attention", highCount)
	}

	if len(pr.TestSelections) > 0 {
		if len(pr.TestSelections) <= 5 {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			line("  - Run %d test(s): %s", len(paths), strings.Join(paths, ", "))
		} else {
			line("  - Run %d test(s) (see full comment for details)", len(pr.TestSelections))
		}
	}
}

// RenderCIAnnotation writes CI-annotation-style output.
func RenderCIAnnotation(w io.Writer, pr *PRAnalysis) {
	findings := DeduplicateFindings(pr.NewFindings)
	for _, f := range findings {
		level := "notice"
		switch f.Severity {
		case "high":
			level = "error"
		case "medium":
			level = "warning"
		}
		fmt.Fprintf(w, "::%s file=%s::%s\n", level, f.Path, f.Explanation)
	}
}

// RenderChangeScopedReport writes a human-readable change-scoped report.
func RenderChangeScopedReport(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	blank := func() { fmt.Fprintln(w) }

	findings := DeduplicateFindings(pr.NewFindings)
	mergeRec, mergeExpl := MergeRecommendation(pr.PostureBand, findings)

	line("Terrain — Change-Scoped Analysis")
	line(strings.Repeat("=", 40))
	blank()

	line("Recommendation:  %s", mergeRec)
	line("Posture:         %s", strings.ToUpper(pr.PostureBand))
	line("Files:           %d changed (%d source, %d test)", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	line("Units:           %d impacted", pr.ImpactedUnitCount)
	line("Gaps:            %d", pr.ProtectionGapCount)
	if len(pr.RecommendedTests) > 0 && pr.TotalTestCount > 0 {
		line("Tests:           %d of %d (%.0f%% reduction)", len(pr.RecommendedTests), pr.TotalTestCount,
			100.0-100.0*float64(len(pr.RecommendedTests))/float64(pr.TotalTestCount))
	}
	line("Reason:          %s", mergeExpl)
	blank()

	directRisk, indirectRisk, existingDebt := ClassifyFindingsDetailed(findings)

	if len(directRisk) > 0 {
		line("New Risks (directly changed)")
		line(strings.Repeat("-", 40))
		for _, f := range directRisk {
			line("  [%s] %s — %s", strings.ToUpper(f.Severity), f.Path, f.Explanation)
		}
		blank()
	}

	if len(indirectRisk) > 0 {
		line("Indirectly Impacted Gaps (%d)", len(indirectRisk))
		line(strings.Repeat("-", 40))
		for _, f := range indirectRisk {
			line("  [%s] %s — %s", strings.ToUpper(f.Severity), f.Path, f.Explanation)
		}
		blank()
	}

	if len(existingDebt) > 0 {
		line("Pre-Existing Issues")
		line(strings.Repeat("-", 40))
		for _, f := range existingDebt {
			line("  [%s] %s — %s", strings.ToUpper(f.Severity), f.Path, f.Explanation)
		}
		blank()
	}

	if len(pr.TestSelections) > 0 {
		line("Recommended Tests (%d)", len(pr.TestSelections))
		line(strings.Repeat("-", 40))
		if pr.SelectionExplanation != "" {
			line("  Strategy: %s", pr.SelectionExplanation)
			blank()
		}
		if len(pr.TestSelections) <= 20 {
			reasons := formatTestReasons(pr.TestSelections)
			for _, t := range pr.TestSelections {
				line("  [%s] %s", t.Confidence, t.Path)
				line("         %s", reasons[t.Path])
			}
		} else {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			for _, g := range GroupTestsByPackage(paths) {
				line("  %s/ — %d test(s)", g.Package, g.Count)
			}
		}
		blank()
	}

	if len(pr.AffectedOwners) > 0 {
		line("Affected Owners: %s", strings.Join(pr.AffectedOwners, ", "))
		blank()
	}

	// AI risk review summary.
	if ai := pr.AI; ai != nil {
		line("AI Risk Review")
		line(strings.Repeat("-", 40))
		line("  Scenarios: %d of %d selected", ai.SelectedScenarios, ai.TotalScenarios)
		if len(ai.ImpactedCapabilities) > 0 {
			line("  Capabilities: %s", strings.Join(ai.ImpactedCapabilities, ", "))
		}
		if len(ai.BlockingSignals) > 0 {
			groups := groupSignalsByFileAndType(ai.BlockingSignals)
			line("  %d new finding(s) on changed files:", len(groups))
			for _, g := range groups {
				summary := humanSummary[g.Type]
				if summary == "" {
					summary = g.Explanation
				}
				loc := g.File
				switch {
				case len(g.Lines) > 0:
					strs := make([]string, len(g.Lines))
					for i, ln := range g.Lines {
						strs[i] = fmt.Sprintf("%d", ln)
					}
					loc = fmt.Sprintf("%s:%s", g.File, strings.Join(strs, ","))
				case len(g.Symbols) > 0:
					loc = fmt.Sprintf("%s (%s)", g.File, strings.Join(g.Symbols, ", "))
				}
				line("    [%s] %s — %s", strings.ToUpper(g.Severity), loc, summary)
				if action := humanAction[g.Type]; action != "" {
					line("      → %s", action)
				}
			}
		}
		if len(ai.UncoveredContexts) > 0 {
			line("  Uncovered AI surfaces: %d", len(ai.UncoveredContexts))
			for _, c := range ai.UncoveredContexts {
				line("    - %s", c)
			}
		}
		blank()
	}

	if len(pr.Limitations) > 0 {
		line("Limitations")
		line(strings.Repeat("-", 40))
		for _, l := range pr.Limitations {
			line("  %s", l)
		}
		blank()
	}
}

// renderAISection renders the AI risk review summary in markdown.
func renderAISection(line func(string, ...any), pr *PRAnalysis) {
	ai := pr.AI
	if ai == nil {
		return
	}

	line("### AI Risk Review")
	line("")

	// Compact context line: capabilities + scenarios in one row.
	// Pre-fix this was two separate stanzas (a bold-label inline label
	// and a plain "Scenarios: X of Y selected" line). One blockquote
	// reads more cleanly and renders as a callout on GitHub.
	contextParts := []string{}
	if len(ai.ImpactedCapabilities) > 0 {
		contextParts = append(contextParts,
			fmt.Sprintf("**Capabilities:** %s", strings.Join(ai.ImpactedCapabilities, ", ")))
	}
	contextParts = append(contextParts,
		fmt.Sprintf("**Scenarios:** %d of %d selected", ai.SelectedScenarios, ai.TotalScenarios))
	line("> %s", strings.Join(contextParts, " · "))
	line("")

	// Blocking signals — grouped by (file, type) so 12 prompt-injection
	// hits across 4 files become 4 bullets, not 12. Each bullet leads
	// with the file:line locator and a plain-language summary instead
	// of detector taxonomy. See ai_signal_humanize.go.
	if len(ai.BlockingSignals) > 0 {
		groups := groupSignalsByFileAndType(ai.BlockingSignals)
		line("**%d new %s introduced by this PR:**", len(groups), pluralize(len(groups), "finding", "findings"))
		line("")
		for _, g := range groups {
			for _, l := range renderGroupedSignal(g) {
				line("%s", l)
			}
		}
		line("")
	}

	// Warning signals follow the same grouping. Wrapped in a details
	// element so they're collapsed by default in GitHub.
	if len(ai.WarningSignals) > 0 {
		groups := groupSignalsByFileAndType(ai.WarningSignals)
		line("<details><summary><b>%d advisory %s</b></summary>", len(groups), pluralize(len(groups), "finding", "findings"))
		line("")
		for _, g := range groups {
			for _, l := range renderGroupedSignal(g) {
				line("%s", l)
			}
		}
		line("")
		line("</details>")
		line("")
	}

	// Impacted scenarios grouped by capability.
	if len(ai.Scenarios) > 0 {
		// Group by capability.
		byCap := map[string][]AIScenarioSummary{}
		var noCap []AIScenarioSummary
		for _, sc := range ai.Scenarios {
			if sc.Capability != "" {
				byCap[sc.Capability] = append(byCap[sc.Capability], sc)
			} else {
				noCap = append(noCap, sc)
			}
		}

		if len(byCap) > 0 || len(noCap) > 0 {
			line("<details><summary>Impacted scenarios (%d)</summary>", len(ai.Scenarios))
			line("")
			// Sort capability keys.
			caps := make([]string, 0, len(byCap))
			for c := range byCap {
				caps = append(caps, c)
			}
			sort.Strings(caps)
			for _, cap := range caps {
				line("**%s:**", cap)
				for _, sc := range byCap[cap] {
					line("- %s — %s", sc.Name, sc.Reason)
				}
			}
			if len(noCap) > 0 {
				for _, sc := range noCap {
					line("- %s — %s", sc.Name, sc.Reason)
				}
			}
			line("")
			line("</details>")
			line("")
		}
	}

	// Uncovered AI surfaces.
	if len(ai.UncoveredContexts) > 0 {
		line("**Changed AI surfaces without eval coverage (%d):**", len(ai.UncoveredContexts))
		line("")
		for _, c := range ai.UncoveredContexts {
			line("- `%s`", c)
		}
		line("")
	}
}

// postureBadge delegates to uitokens.BracketedVerdict so the badge
// vocabulary is owned by the design system. Track 10.2.
func postureBadge(band string) string {
	return uitokens.BracketedVerdict(band)
}

// severityIcon delegates to uitokens.BracketedSeverity so the badge
// vocabulary is owned by the design system. Track 10.2 — every
// renderer that emits user-visible severity should consume from
// uitokens rather than carrying its own switch. Pre-Track-10.2 this
// function returned its own bracketed strings; the wrapper is kept
// (rather than inlining the call) so internal helpers like
// renderFindingCard remain unchanged and the diff stays surgical.
func severityIcon(severity string) string {
	return uitokens.BracketedSeverity(severity)
}

// formatSuitePercent renders selected/total as a percentage with
// honest precision for small fractions. Pre-fix the integer-division
// formula floored 7-of-796 to "0% of suite" — adopters seeing
// "0%" reasonably wonder whether selection ran at all. Now sub-1%
// fractions render as "<1%", and values ≥1% render as integer
// percentages.
func formatSuitePercent(selected, total int) string {
	if total <= 0 {
		return "—"
	}
	if selected <= 0 {
		return "0%"
	}
	pct := 100 * selected / total
	if pct == 0 {
		return "<1%"
	}
	return fmt.Sprintf("%d%%", pct)
}

func formatSeverityCounts(counts map[string]int) []string {
	var parts []string
	for _, sev := range []string{"high", "medium", "low"} {
		if c, ok := counts[sev]; ok && c > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", c, sev))
		}
	}
	return parts
}

func deduplicateReasons(reasons []string) string {
	seen := map[string]int{}
	var unique []string
	for _, r := range reasons {
		seen[r]++
		if seen[r] == 1 {
			unique = append(unique, r)
		}
	}
	var parts []string
	for _, r := range unique {
		if seen[r] > 1 {
			parts = append(parts, fmt.Sprintf("%s (%dx)", r, seen[r]))
		} else {
			parts = append(parts, r)
		}
	}
	return strings.Join(parts, "; ")
}

func formatTestReasons(selections []TestSelection) map[string]string {
	reasons := map[string]string{}
	unitTestCount := map[string]int{}
	for _, t := range selections {
		for _, uid := range t.CoversUnits {
			unitTestCount[uid]++
		}
	}
	totalTests := len(selections)
	for _, t := range selections {
		reasons[t.Path] = formatSingleTestReason(t, unitTestCount, totalTests)
	}
	return reasons
}

func formatSingleTestReason(t TestSelection, unitTestCount map[string]int, totalTests int) string {
	unitNames := extractUnitNames(t.CoversUnits)
	if len(unitNames) == 0 {
		if len(t.Reasons) > 0 {
			return deduplicateReasons(t.Reasons)
		}
		return t.Relevance
	}
	var unique, shared []string
	for _, uid := range t.CoversUnits {
		name := uid
		if idx := strings.LastIndex(uid, ":"); idx >= 0 {
			name = uid[idx+1:]
		}
		if unitTestCount[uid] == 1 {
			unique = append(unique, name)
		} else {
			shared = append(shared, name)
		}
	}
	unique = deduplicateStrings(unique)
	shared = deduplicateStrings(shared)
	label := "covers"
	if t.Confidence == "exact" {
		label = "exact coverage of"
	}
	const maxDisplay = 3
	if len(unique) > 0 {
		var why string
		if len(unique) <= maxDisplay {
			why = fmt.Sprintf("%s %s", label, formatUnitList(unique))
		} else {
			why = fmt.Sprintf("%s %s + %d more", label, formatUnitList(unique[:maxDisplay]), len(unique)-maxDisplay)
		}
		return why
	}
	if len(unitNames) <= maxDisplay {
		return fmt.Sprintf("%s %s", label, formatUnitList(unitNames))
	}
	return fmt.Sprintf("%s %s + %d more", label, formatUnitList(unitNames[:maxDisplay]), len(unitNames)-maxDisplay)
}

// formatUnitList renders unit names as a comma-separated inline code list.
func formatUnitList(names []string) string {
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "`" + n + "`"
	}
	return strings.Join(parts, ", ")
}

func deduplicateStrings(ss []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range ss {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func extractUnitNames(unitIDs []string) []string {
	if len(unitIDs) == 0 {
		return nil
	}
	seen := map[string]bool{}
	var names []string
	for _, id := range unitIDs {
		name := id
		if idx := strings.LastIndex(id, ":"); idx >= 0 {
			name = id[idx+1:]
		}
		if name != "" && !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	return names
}
