package changescope

import (
	"fmt"
	"io"
	"strings"
)

// RenderPRSummaryMarkdown writes a PR-ready markdown summary.
func RenderPRSummaryMarkdown(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	line("## Terrain — Change Analysis")
	line("")

	// Posture badge.
	badge := postureBadge(pr.PostureBand)
	line("**Posture:** %s %s", badge, strings.ToUpper(pr.PostureBand))
	line("")

	// Summary stats.
	line("| Metric | Count |")
	line("|--------|-------|")
	line("| Changed files | %d |", pr.ChangedFileCount)
	line("| Changed source files | %d |", pr.ChangedSourceCount)
	line("| Changed test files | %d |", pr.ChangedTestCount)
	line("| Impacted code units | %d |", pr.ImpactedUnitCount)
	line("| Protection gaps | %d |", pr.ProtectionGapCount)
	line("")

	// Findings.
	if len(pr.NewFindings) > 0 {
		line("### Findings")
		line("")
		limit := 10
		if len(pr.NewFindings) < limit {
			limit = len(pr.NewFindings)
		}
		for _, f := range pr.NewFindings[:limit] {
			icon := severityIcon(f.Severity)
			line("- %s **%s** `%s`: %s", icon, f.Type, f.Path, f.Explanation)
			if f.SuggestedAction != "" {
				line("  - Action: %s", f.SuggestedAction)
			}
		}
		if len(pr.NewFindings) > limit {
			line("- ... and %d more finding(s)", len(pr.NewFindings)-limit)
		}
		line("")
	}

	// Recommended tests with reasoning.
	if len(pr.TestSelections) > 0 {
		line("### Recommended Tests")
		line("")
		if pr.SelectionExplanation != "" {
			line("*%s*", pr.SelectionExplanation)
			line("")
		}
		limit := 15
		if len(pr.TestSelections) < limit {
			limit = len(pr.TestSelections)
		}
		reasons := formatTestReasons(pr.TestSelections)
		line("| Test | Confidence | Why |")
		line("|------|------------|-----|")
		for _, t := range pr.TestSelections[:limit] {
			line("| `%s` | %s | %s |", t.Path, t.Confidence, reasons[t.Path])
		}
		if len(pr.TestSelections) > limit {
			line("")
			line("...and %d more test(s).", len(pr.TestSelections)-limit)
		}
		line("")
	} else if len(pr.RecommendedTests) > 0 {
		line("### Recommended Tests")
		line("")
		limit := 15
		if len(pr.RecommendedTests) < limit {
			limit = len(pr.RecommendedTests)
		}
		for _, t := range pr.RecommendedTests[:limit] {
			line("- `%s`", t)
		}
		if len(pr.RecommendedTests) > limit {
			line("- ... and %d more", len(pr.RecommendedTests)-limit)
		}
		line("")
	}

	// Affected owners.
	if len(pr.AffectedOwners) > 0 {
		line("### Affected Owners")
		line("")
		for _, o := range pr.AffectedOwners {
			line("- %s", o)
		}
		line("")
	}

	// Limitations.
	if len(pr.Limitations) > 0 {
		line("<details><summary>Limitations</summary>")
		line("")
		for _, l := range pr.Limitations {
			line("- %s", l)
		}
		line("")
		line("</details>")
		line("")
	}

	line("---")
	line("*Generated by [Terrain](https://github.com/pmclSF/terrain) — test system intelligence platform*")
}

// RenderPRCommentConcise writes a concise PR comment suitable for inline use.
func RenderPRCommentConcise(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	badge := postureBadge(pr.PostureBand)
	line("%s **Terrain:** %s", badge, pr.Summary)

	if len(pr.NewFindings) > 0 {
		highCount := 0
		for _, f := range pr.NewFindings {
			if f.Severity == "high" {
				highCount++
			}
		}
		if highCount > 0 {
			line("  - %d high-severity finding(s) require attention", highCount)
		}
	}

	if len(pr.TestSelections) > 0 {
		paths := make([]string, 0, len(pr.TestSelections))
		for _, t := range pr.TestSelections {
			paths = append(paths, t.Path)
		}
		line("  - Run %d test(s): %s", len(paths), strings.Join(paths, ", "))
	} else if len(pr.RecommendedTests) > 0 {
		line("  - Run: %s", strings.Join(pr.RecommendedTests, ", "))
	}
}

// RenderCIAnnotation writes CI-annotation-style output.
func RenderCIAnnotation(w io.Writer, pr *PRAnalysis) {
	for _, f := range pr.NewFindings {
		level := "notice"
		switch f.Severity {
		case "high":
			level = "error"
		case "medium":
			level = "warning"
		}
		fmt.Fprintf(w, "::%s file=%s::%s\n", level, f.Path, f.Explanation)
	}
}

// RenderChangeScopedReport writes a human-readable change-scoped report.
func RenderChangeScopedReport(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	blank := func() { fmt.Fprintln(w) }

	line("Terrain — Change-Scoped Analysis")
	line(strings.Repeat("=", 40))
	blank()

	line("Posture:   %s", strings.ToUpper(pr.PostureBand))
	line("Files:     %d changed (%d source, %d test)", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	line("Units:     %d impacted", pr.ImpactedUnitCount)
	line("Gaps:      %d", pr.ProtectionGapCount)
	blank()

	if len(pr.NewFindings) > 0 {
		line("Findings")
		line(strings.Repeat("-", 40))
		for _, f := range pr.NewFindings {
			line("  [%s] %s — %s", strings.ToUpper(f.Severity), f.Path, f.Explanation)
		}
		blank()
	}

	if len(pr.TestSelections) > 0 {
		line("Recommended Tests")
		line(strings.Repeat("-", 40))
		if pr.SelectionExplanation != "" {
			line("  Strategy: %s", pr.SelectionExplanation)
			blank()
		}
		reasons := formatTestReasons(pr.TestSelections)
		for _, t := range pr.TestSelections {
			line("  [%s] %s", t.Confidence, t.Path)
			line("         %s", reasons[t.Path])
		}
		blank()
	} else if len(pr.RecommendedTests) > 0 {
		line("Recommended Tests")
		line(strings.Repeat("-", 40))
		for _, t := range pr.RecommendedTests {
			line("  %s", t)
		}
		blank()
	}

	if len(pr.AffectedOwners) > 0 {
		line("Affected Owners: %s", strings.Join(pr.AffectedOwners, ", "))
		blank()
	}

	if len(pr.Limitations) > 0 {
		line("Limitations")
		line(strings.Repeat("-", 40))
		for _, l := range pr.Limitations {
			line("  %s", l)
		}
		blank()
	}
}

func postureBadge(band string) string {
	switch band {
	case "well_protected":
		return "[PASS]"
	case "partially_protected":
		return "[WARN]"
	case "weakly_protected":
		return "[RISK]"
	case "high_risk":
		return "[FAIL]"
	case "evidence_limited":
		return "[INFO]"
	default:
		return "[????]"
	}
}

func deduplicateReasons(reasons []string) string {
	seen := map[string]int{}
	var unique []string
	for _, r := range reasons {
		seen[r]++
		if seen[r] == 1 {
			unique = append(unique, r)
		}
	}
	var parts []string
	for _, r := range unique {
		if seen[r] > 1 {
			parts = append(parts, fmt.Sprintf("%s (%dx)", r, seen[r]))
		} else {
			parts = append(parts, r)
		}
	}
	return strings.Join(parts, "; ")
}

// formatTestReasons builds per-test "Why" strings for all selections.
// When multiple tests cover the same units, it highlights what's unique
// to each test so reviewers can tell them apart.
func formatTestReasons(selections []TestSelection) map[string]string {
	reasons := map[string]string{}

	// Count how many tests cover each unit ID.
	unitTestCount := map[string]int{}
	for _, t := range selections {
		for _, uid := range t.CoversUnits {
			unitTestCount[uid]++
		}
	}
	totalTests := len(selections)

	for _, t := range selections {
		reasons[t.Path] = formatSingleTestReason(t, unitTestCount, totalTests)
	}
	return reasons
}

// formatSingleTestReason builds a reason string for one test, preferring
// unique units (covered only by this test) over shared ones.
func formatSingleTestReason(t TestSelection, unitTestCount map[string]int, totalTests int) string {
	unitNames := extractUnitNames(t.CoversUnits)

	if len(unitNames) == 0 {
		if len(t.Reasons) > 0 {
			return deduplicateReasons(t.Reasons)
		}
		return t.Relevance
	}

	// Split into unique (only this test covers it) and shared units.
	var unique, shared []string
	for _, uid := range t.CoversUnits {
		name := uid
		if idx := strings.LastIndex(uid, ":"); idx >= 0 {
			name = uid[idx+1:]
		}
		if unitTestCount[uid] == 1 {
			unique = append(unique, name)
		} else {
			shared = append(shared, name)
		}
	}
	// Deduplicate names (different paths can have same name).
	unique = deduplicateStrings(unique)
	shared = deduplicateStrings(shared)

	label := "covers"
	if t.Confidence == "exact" {
		label = "exact coverage of"
	}

	const maxDisplay = 4

	// If there are unique units, lead with those — they're the differentiator.
	if len(unique) > 0 {
		var why string
		if len(unique) <= maxDisplay {
			why = fmt.Sprintf("%s `%s`", label, strings.Join(unique, "`, `"))
		} else {
			why = fmt.Sprintf("%s `%s` + %d more", label, strings.Join(unique[:maxDisplay], "`, `"), len(unique)-maxDisplay)
		}
		if len(shared) > 0 {
			why += fmt.Sprintf(" (+ %d shared)", len(shared))
		}
		return why
	}

	// All units are shared — show names but note they're shared across tests.
	if len(unitNames) <= maxDisplay {
		why := fmt.Sprintf("%s `%s`", label, strings.Join(unitNames, "`, `"))
		if totalTests > 1 {
			why += fmt.Sprintf(" (shared across %d tests)", unitTestCount[t.CoversUnits[0]])
		}
		return why
	}
	shown := strings.Join(unitNames[:maxDisplay], "`, `")
	why := fmt.Sprintf("%s `%s` + %d more", label, shown, len(unitNames)-maxDisplay)
	if totalTests > 1 {
		why += fmt.Sprintf(" (shared across %d tests)", unitTestCount[t.CoversUnits[0]])
	}
	return why
}

func deduplicateStrings(ss []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range ss {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

// extractUnitNames extracts human-readable names from code unit IDs.
// Unit IDs have the format "path:Name" — we extract just the Name part.
func extractUnitNames(unitIDs []string) []string {
	if len(unitIDs) == 0 {
		return nil
	}
	seen := map[string]bool{}
	var names []string
	for _, id := range unitIDs {
		name := id
		if idx := strings.LastIndex(id, ":"); idx >= 0 {
			name = id[idx+1:]
		}
		if name != "" && !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	return names
}

func severityIcon(severity string) string {
	switch severity {
	case "high":
		return "[HIGH]"
	case "medium":
		return "[MED]"
	case "low":
		return "[LOW]"
	default:
		return "[---]"
	}
}
