package changescope

import (
	"fmt"
	"io"
	"sort"
	"strings"
	"sync"

	"github.com/pmclSF/terrain/internal/models"
	"github.com/pmclSF/terrain/internal/prtemplates"
	"github.com/pmclSF/terrain/internal/signals"
	"github.com/pmclSF/terrain/internal/uitokens"
)

// RenderPRSummaryMarkdown writes a PR-ready markdown summary optimized
// for human review and merge decisions.
//
// 0.2 layout — designed for visual scanability on GitHub:
//
//	## Terrain — <verdict>
//
//	> <one-sentence why> (blockquote callout)
//
//	| Metric | Value |
//	| ... compact 2-column table ... |
//
//	--- (horizontal rule between major sections)
//
//	### Coverage gaps in changed code
//
//	- **`path/to/file.ts`** [HIGH] — <plain-language description>
//
//	---
//
//	### Recommended tests
//
//	---
//
//	### AI Risk Review
//
//	---
//
//	<sub>Owners · Generated by Terrain · ...</sub>  (small footer)
//
// Each section is gated on having content, so tiny PRs stay tiny. The
// horizontal rules (`---`) give the comment visual rhythm — every
// section is a discrete card rather than a blob.
func RenderPRSummaryMarkdown(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	hr := func() {
		line("---")
		line("")
	}

	// Deduplicate findings at render time (safeguard).
	findings := DeduplicateFindings(pr.NewFindings)
	directRisk, indirectRisk, existingDebt := ClassifyFindingsDetailed(findings)

	// Merge recommendation.
	mergeRec, mergeExpl := MergeRecommendation(pr.PostureBand, findings)

	// --- Header — H2 verdict + blockquote subtitle. ---
	// Blockquote is more visually distinct than the previous italic line
	// and renders as a colored callout on GitHub.
	badge := postureBadge(pr.PostureBand)
	line("## %s Terrain — %s", badge, mergeRec)
	line("")
	if mergeExpl != "" {
		line("> %s", mergeExpl)
		line("")
	}

	// --- Compact metrics table ---
	// Bold labels in the left column for visual hierarchy. The middle-
	// dot separator (·) replaces commas in compound stats so the cell
	// content reads cleanly.
	line("| Metric | Value |")
	line("|---|---|")
	line("| **Changed files** | %d (%d source · %d test) |", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	if pr.ImpactedUnitCount > 0 {
		line("| **Impacted units** | %d |", pr.ImpactedUnitCount)
	}
	if pr.ProtectionGapCount > 0 {
		line("| **Protection gaps** | %d |", pr.ProtectionGapCount)
	}
	if len(pr.RecommendedTests) > 0 {
		if pr.TotalTestCount > 0 {
			line("| **Tests selected** | %d of %d (%s of suite) |",
				len(pr.RecommendedTests), pr.TotalTestCount,
				formatSuitePercent(len(pr.RecommendedTests), pr.TotalTestCount))
		} else {
			line("| **Tests selected** | %d |", len(pr.RecommendedTests))
		}
	}
	line("")

	// --- New risks introduced by this PR (directly changed files) ---
	if len(directRisk) > 0 {
		hr()
		line("### Coverage gaps in changed code")
		line("")
		// Protection-gap findings (no SignalType) keep the old N-cap
		// + overflow-summary behavior; co-fires across files don't
		// collapse because each file is its own surface. Detector-
		// bearing findings flow through renderFindingsCardsByDetector
		// (the per-detector visibility floor) which is consumed by the
		// slash-command PR surface.
		renderFindingsCards(line, directRisk, 10)
	}

	// --- Indirectly impacted gaps (collapsed) ---
	if len(indirectRisk) > 0 {
		line("<details><summary><b>%d indirectly impacted protection %s</b></summary>", len(indirectRisk), pluralize(len(indirectRisk), "gap", "gaps"))
		line("")
		renderFindingsCards(line, indirectRisk, 5)
		line("</details>")
		line("")
	}

	// --- Pre-existing gaps touched by this change ---
	//
	// existingDebt contains existing_signal findings (SignalType-bearing,
	// detector-emitted). Apply the per-detector visibility floor:
	// every detector that fired gets at least one card; co-fires within
	// a detector collapse to "↳ +N more". Small lists (≤3) skip the
	// <details> wrap so the reader doesn't have to click through
	// trivial findings.
	if len(existingDebt) > 0 {
		if len(existingDebt) <= 3 {
			hr()
			line("### Pre-existing issues (%d)", len(existingDebt))
			line("")
			renderFindingsCardsByDetector(line, existingDebt, 1)
		} else {
			line("<details><summary><b>%d pre-existing %s on changed files</b></summary>", len(existingDebt), pluralize(len(existingDebt), "issue", "issues"))
			line("")
			renderFindingsCardsByDetector(line, existingDebt, 1)
			line("</details>")
			line("")
		}
	}

	// --- Test recommendations ---
	if len(pr.TestSelections) > 0 || len(pr.RecommendedTests) > 0 {
		hr()
		renderTestRecommendations(line, pr)
	}

	// --- AI Risk Review ---
	if pr.AI != nil {
		hr()
		renderAISection(line, pr)
	}

	// --- Empty-PR celebration callout ---
	// When the PR introduces no new findings AND has no AI risk
	// section AND no recommended tests (because the change has no
	// measurable impact), the markdown above is just header +
	// metrics. Add a small designed "all clear" callout so the
	// reader sees that this is the *deliberate* shape of a clean
	// PR, not a malfunction.
	if isEmptyPR(pr) {
		hr()
		line("> ✓ **All clear.** No new findings introduced; no protection gaps identified in changed code.")
		line(">")
		line("> *Run `terrain compare` over time to track posture; this clean state is the bar to hold.*")
		line("")
	}

	// --- Footer (owners + limitations + branding) ---
	// Combined into a single small-text footer so individual elements
	// don't compete for attention with the main content.
	hr()
	footerParts := []string{}
	if len(pr.AffectedOwners) > 0 {
		footerParts = append(footerParts, fmt.Sprintf("**Owners:** %s", strings.Join(pr.AffectedOwners, ", ")))
	}
	if len(footerParts) > 0 {
		line("%s", strings.Join(footerParts, " · "))
		line("")
	}
	if len(pr.Limitations) > 0 {
		line("<details><summary><b>Limitations</b></summary>")
		line("")
		for _, l := range pr.Limitations {
			line("- %s", l)
		}
		line("")
		line("</details>")
		line("")
	}
	line("<sub>Generated by [Terrain](https://github.com/pmclSF/terrain) · `terrain pr --json` for machine-readable output</sub>")
}

// renderFindingsCards renders up to `limit` findings as cards in the
// emitted order, with a "+N more (severity counts)" overflow summary
// when len(findings) > limit. This is the protection-gap render path:
// each finding is a separate file, so co-fires don't collapse — the
// cap is just a comment-length bound.
//
// Detector-bearing findings (with SignalType) should use
// renderFindingsCardsByDetector instead, which implements the
// per-detector visibility floor.
//
// Trails a blank line so the next section header has breathing room.
// renderFindingsByPath groups findings by file path and renders one
// header per path followed by indented [SEV] explanation lines. Keeps
// the wall-of-same-path effect from drowning multi-rule files (a
// repo with three AI surfaces × three AI rules previously printed the
// same path nine times; now it prints once with nine indented bullets).
func renderFindingsByPath(line func(string, ...any), findings []ChangeScopedFinding) {
	// Group preserving first-seen path order so the output is stable.
	type group struct {
		path  string
		items []ChangeScopedFinding
	}
	var groups []*group
	idx := map[string]*group{}
	for _, f := range findings {
		g, ok := idx[f.Path]
		if !ok {
			g = &group{path: f.Path}
			idx[f.Path] = g
			groups = append(groups, g)
		}
		g.items = append(g.items, f)
	}
	for _, g := range groups {
		if len(g.items) == 1 {
			f := g.items[0]
			line("  %s %s — %s", uitokens.BracketedSeverity(f.Severity), f.Path, collapseLinebreaks(f.Explanation))
			continue
		}
		line("  %s", g.path)
		for _, f := range g.items {
			line("    %s %s", uitokens.BracketedSeverity(f.Severity), collapseLinebreaks(f.Explanation))
		}
	}
}

func renderFindingsCards(line func(string, ...any), findings []ChangeScopedFinding, limit int) {
	if len(findings) < limit {
		limit = len(findings)
	}
	for _, f := range findings[:limit] {
		renderFindingCard(line, f)
	}
	if len(findings) > limit {
		overflow := SummarizeFindingsBySeverity(findings[limit:])
		parts := formatSeverityCounts(overflow)
		line("- _...and %d more (%s)_", len(findings)-limit, strings.Join(parts, ", "))
	}
	line("") // visual breathing room before the next section
}

// renderFindingsCardsByDetector renders findings grouped by detector
// class so every detector that fired contributes at least one card.
// Within a group, the highest-severity finding is shown; co-fires
// collapse to a "↳ +N more" link after the headline card. Group order
// is highest-severity-of-group first, then alphabetical by detector
// key.
//
// Per-detector visibility floor: at least one finding from every
// detector that fired must appear in the surface. Severity ordering
// can collapse co-firings within a detector; never across detectors.
//
// `cardsPerGroup` is the per-group cap (no group renders more than
// `cardsPerGroup` individual cards before the +N collapse). Passing
// 0 or negative defaults to 1 (the "headline + +N" shape).
// Trails a blank line so the next section header has breathing room.
//
// Consumed by the slash-command PR-comment surface; protection-gap
// findings keep the older renderFindingsCards path because each gap
// is a different file.
func renderFindingsCardsByDetector(line func(string, ...any), findings []ChangeScopedFinding, cardsPerGroup int) {
	if len(findings) == 0 {
		line("")
		return
	}
	if cardsPerGroup <= 0 {
		cardsPerGroup = 1
	}

	groups := groupFindingsByDetector(findings)
	for _, g := range groups {
		visible := cardsPerGroup
		if visible > len(g.Findings) {
			visible = len(g.Findings)
		}
		for _, f := range g.Findings[:visible] {
			renderFindingCard(line, f)
		}
		if rest := len(g.Findings) - visible; rest > 0 {
			line("  ↳ _+%d more in this detector — see `terrain explain %s`_", rest, g.Key)
		}
	}
	line("") // visual breathing room before the next section
}

// findingGroup is a per-detector cluster of findings, sorted within
// the group by severity descending so the "headline" finding is
// findings[0].
type findingGroup struct {
	// Key is the grouping key: SignalType when set, else the finding's
	// Type (e.g. "protection_gap"). Surfaces in the +N collapse link.
	Key string
	// MaxSeverity is the worst severity in the group. Drives inter-
	// group ordering so the highest-severity detector renders first.
	MaxSeverity string
	// Findings is the in-group list, severity-sorted (highest first).
	Findings []ChangeScopedFinding
}

// groupFindingsByDetector buckets findings by detector identity.
// SignalType-bearing findings cluster by SignalType so co-fires of
// the same rule collapse to one card + a +N link. Protection-gap
// findings (Type="protection_gap", no SignalType) cluster by FILE
// instead — each gap is a different uncovered surface; collapsing
// them by Type would hide the per-file severity, defeating the
// purpose of the report. Groups are sorted by max-severity-in-group
// descending, ties broken by key ascending.
func groupFindingsByDetector(findings []ChangeScopedFinding) []findingGroup {
	idx := map[string]*findingGroup{}
	var keys []string
	for _, f := range findings {
		key := f.SignalType
		if key == "" {
			// Protection-gap findings have no SignalType. Group by file
			// path so each gap renders as its own card.
			if f.Path != "" {
				key = "file:" + f.Path
			} else {
				key = f.Type
			}
		}
		if key == "" {
			key = "_"
		}
		g, ok := idx[key]
		if !ok {
			g = &findingGroup{Key: key, MaxSeverity: f.Severity}
			idx[key] = g
			keys = append(keys, key)
		}
		if findingSeverityRank(f.Severity) > findingSeverityRank(g.MaxSeverity) {
			g.MaxSeverity = f.Severity
		}
		g.Findings = append(g.Findings, f)
	}
	// Sort within each group by severity descending so the headline
	// card is the worst finding the detector emitted.
	for _, g := range idx {
		sort.SliceStable(g.Findings, func(i, j int) bool {
			return findingSeverityRank(g.Findings[i].Severity) > findingSeverityRank(g.Findings[j].Severity)
		})
	}
	// Sort groups by max-severity desc, then key asc.
	out := make([]findingGroup, 0, len(keys))
	for _, k := range keys {
		out = append(out, *idx[k])
	}
	sort.SliceStable(out, func(i, j int) bool {
		if out[i].MaxSeverity != out[j].MaxSeverity {
			return findingSeverityRank(out[i].MaxSeverity) > findingSeverityRank(out[j].MaxSeverity)
		}
		return out[i].Key < out[j].Key
	})
	return out
}

// findingSeverityRank maps the lowercase severity string to an
// orderable rank. Mirrors the ai_signal_humanize.severityRank helper
// but lives here so render.go doesn't depend on the AI helpers when
// rendering non-AI findings.
func findingSeverityRank(s string) int {
	switch strings.ToLower(s) {
	case "critical":
		return 5
	case "high":
		return 4
	case "medium":
		return 3
	case "low":
		return 2
	case "info":
		return 1
	}
	return 0
}

// renderFindingCard emits one finding as a card-style bullet:
//
//   - **`path/to/file.go`** [BLOCK|GATE|WATCH|NOTE] — <explanation>
//     → <suggested action>
//
// Suggested action is omitted when the finding doesn't carry one.
// Info-tier findings (PRLabel == "") render with no badge — they
// drop from the PR surface entirely, but the rendering helpers don't
// filter at this level; the caller (renderFindingsCards,
// renderFindingsCardsByDetector) decides whether to emit the card
// at all.
//
// The tier is looked up from the finding's SignalType via the
// manifest (signals.IsObservabilityTier). Protection-gap findings
// (no SignalType) default to gate-tier — they're coverage issues
// meant to block.
func renderFindingCard(line func(string, ...any), f ChangeScopedFinding) {
	renderFindingCardWithHistory(line, f, getActiveHistoryStore())
}

// renderFindingCardWithHistory is the history-aware form. The PR-
// comment top-level renderer loads a findinghistory.Store once and
// passes it through; tests + non-PR render paths pass nil. When the
// store reports ShouldDemote(SignalType, File), the badge renders
// as the observability label regardless of the manifest tier —
// chronically-firing-without-dismiss findings fade to the
// observability footer.
func renderFindingCardWithHistory(line func(string, ...any), f ChangeScopedFinding, historyStore HistoryStore) {
	badge := prLabelBadgeWithHistory(f, historyStore)
	summary, action := summaryAndActionForFinding(f)
	line("- **`%s`** %s — %s", f.Path, badge, summary)
	if action != "" {
		line("  → %s", action)
	}
	// Hidden marker for the slash-receiver proxy to resolve /dismiss
	// replies. GitHub renders HTML comments as invisible, so adopters
	// reading the PR see no extra noise; the proxy grep's the parent
	// comment for `terrain:finding=` and injects the id into the
	// X-Terrain-Finding-Id header before terrain sees the event.
	//
	// Omitted for protection-gap and legacy detectors that don't yet
	// populate FindingID — the user-facing `finding:<id>` keyword
	// fallback covers those.
	if f.FindingID != "" {
		// Sanitize embedded "--" inside the id. HTML comments forbid
		// "--" inside the comment body; an id like
		// `staticSkippedTest-unconditional@src/foo--bar.ts:L10#abc`
		// would prematurely close the comment, leaking markup into the
		// PR rendering. Replace "--" with "__" — the proxy reverses
		// before posting to the dispatcher.
		safeID := strings.ReplaceAll(f.FindingID, "--", "__")
		line("  <!-- terrain:finding=%s -->", safeID)
	}
}

// HistoryStore is the minimal interface the renderer needs from
// internal/findinghistory.Store. Declared locally so the
// changescope package doesn't import internal/findinghistory
// directly — callers in cmd/terrain pass the concrete store
// through.
type HistoryStore interface {
	ShouldDemote(ruleID, file string) bool
}

// activeHistoryStore is the per-invocation history store the
// top-level renderer (RenderPRSummaryMarkdownWithHistory) sets and
// unsets. Subordinate helpers (renderFindingCard,
// renderFindingsCardsByDetector) consult it without needing extra
// parameters that would churn every call site.
//
// Protected by activeHistoryStoreMu for the race detector's benefit:
// the CLI invokes the renderer once per process, but tests run with
// t.Parallel() and trip the race detector without a guard. A future
// long-running server that renders for multiple PRs in parallel
// must thread the store through call arguments instead.
var (
	activeHistoryStoreMu sync.Mutex
	activeHistoryStore   HistoryStore
)

func setActiveHistoryStore(s HistoryStore) (prev HistoryStore) {
	activeHistoryStoreMu.Lock()
	defer activeHistoryStoreMu.Unlock()
	prev = activeHistoryStore
	activeHistoryStore = s
	return prev
}

func getActiveHistoryStore() HistoryStore {
	activeHistoryStoreMu.Lock()
	defer activeHistoryStoreMu.Unlock()
	return activeHistoryStore
}

// RenderPRSummaryMarkdownWithHistory is the history-aware form of
// RenderPRSummaryMarkdown. When `hist` is non-nil, every
// SignalType-bearing card that the store reports as ShouldDemote
// renders as the observability (WATCH) label regardless of the
// manifest tier — chronically-firing-without-dismiss findings fade
// to the observability footer.
//
// Pass nil for `hist` to get the legacy behavior (or call
// RenderPRSummaryMarkdown directly).
func RenderPRSummaryMarkdownWithHistory(w io.Writer, pr *PRAnalysis, hist HistoryStore) {
	prev := setActiveHistoryStore(hist)
	defer setActiveHistoryStore(prev)
	RenderPRSummaryMarkdown(w, pr)
}

// summaryAndActionForFinding looks up a curated template for the
// finding's SignalType in prtemplates and returns the template's
// Summary + Action. Falls back to the detector-emitted Explanation
// / SuggestedAction when no template is registered — protection-gap
// findings (no SignalType) always fall through.
//
// Hard-wraps from YAML block scalars or detector source strings are
// collapsed to a single line so the markdown bullet doesn't break
// across paragraphs on GitHub. Leading `[signalType]` prefixes are
// stripped — the same id is already embedded in the hidden
// `terrain:finding=` marker and the PR-comment badge.
func summaryAndActionForFinding(f ChangeScopedFinding) (summary, action string) {
	summary = collapseLinebreaks(f.Explanation)
	action = collapseLinebreaks(f.SuggestedAction)
	if f.SignalType == "" {
		return
	}
	// Strip a redundant `[signalType]` prefix some detectors include.
	summary = stripSignalTypePrefix(summary, f.SignalType)
	reg, err := prtemplates.Default()
	if err != nil || reg == nil {
		return
	}
	tpl, ok := reg.Get(f.SignalType)
	if !ok {
		return
	}
	summary = collapseLinebreaks(strings.TrimSpace(tpl.Summary))
	action = collapseLinebreaks(strings.TrimSpace(tpl.Action))
	return
}

// prLabelBadge returns the bracketed user-visible PR-comment label
// (BLOCK / GATE / WATCH / NOTE) for a finding. Empty string when the
// finding should drop from the PR surface (info-tier).
func prLabelBadge(f ChangeScopedFinding) string {
	return prLabelBadgeWithHistory(f, nil)
}

// prLabelBadgeWithHistory is the history-aware form. When the store
// reports the (SignalType, File) pair as ShouldDemote, the badge
// renders as observability (WATCH) regardless of the manifest tier.
func prLabelBadgeWithHistory(f ChangeScopedFinding, historyStore HistoryStore) string {
	tier := tierForFinding(f)
	if historyStore != nil && f.SignalType != "" && f.Path != "" {
		if historyStore.ShouldDemote(f.SignalType, f.Path) {
			tier = "observability"
		}
	}
	return uitokens.BracketedPRLabel(tier, f.Severity)
}

// tierForFinding returns "gate" or "observability" for a finding.
// SignalType-bearing findings consult the manifest; protection-gap
// findings (no SignalType) default to gate.
func tierForFinding(f ChangeScopedFinding) string {
	if f.SignalType == "" {
		return "gate"
	}
	if signals.IsObservabilityTier(models.SignalType(f.SignalType)) {
		return "observability"
	}
	return "gate"
}

// pluralize returns "finding" or "findings" based on count. Used to
// avoid the awkward "finding(s)" notation in user-visible headers.
func pluralize(n int, singular, plural string) string {
	if n == 1 {
		return singular
	}
	return plural
}

// renderTestRecommendations renders the test recommendations section.
func renderTestRecommendations(line func(string, ...any), pr *PRAnalysis) {
	if len(pr.TestSelections) > 0 {
		line("### Recommended tests")
		line("")
		if pr.SelectionExplanation != "" {
			line("*%s*", pr.SelectionExplanation)
			line("")
		}

		// Confidence histogram — audit-named gap
		// (pr_change_scoped.E3 observability). Surfaces the
		// distribution of test-selection confidence so reviewers
		// see at a glance whether the recommended set is mostly
		// strong matches or mostly inferred coverage.
		if hist := buildConfidenceHistogram(pr.TestSelections); hist != "" {
			line("%s", hist)
			line("")
		}

		if len(pr.TestSelections) <= 15 {
			reasons := formatTestReasons(pr.TestSelections)
			line("| Test | Confidence | Why |")
			line("|------|------------|-----|")
			for _, t := range pr.TestSelections {
				line("| `%s` | %s | %s |", t.Path, t.Confidence, reasons[t.Path])
			}
		} else {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			groups := GroupTestsByPackage(paths)
			line("| Package | Tests | Sample |")
			line("|---------|-------|--------|")
			for _, g := range groups {
				sample := g.Files[0]
				if len(g.Files) > 1 {
					sample += " ..."
				}
				line("| `%s` | %d | `%s` |", g.Package, g.Count, sample)
			}
		}
		line("")
	} else if len(pr.RecommendedTests) > 0 {
		line("### Recommended tests")
		line("")
		if len(pr.RecommendedTests) <= 15 {
			for _, t := range pr.RecommendedTests {
				line("- `%s`", t)
			}
		} else {
			groups := GroupTestsByPackage(pr.RecommendedTests)
			for _, g := range groups {
				line("- `%s/` — %d %s", g.Package, g.Count, pluralize(g.Count, "test", "tests"))
			}
		}
		line("")
	}
}

// RenderPRCommentConcise writes a concise one-line PR comment.
func RenderPRCommentConcise(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}

	findings := DeduplicateFindings(pr.NewFindings)
	mergeRec, _ := MergeRecommendation(pr.PostureBand, findings)
	badge := postureBadge(pr.PostureBand)
	line("%s **Terrain:** %s — %s", badge, mergeRec, pr.Summary)

	highCount := 0
	for _, f := range findings {
		if f.Severity == "high" {
			highCount++
		}
	}
	if highCount > 0 {
		line("  - %d high-severity %s require attention", highCount, pluralize(highCount, "finding", "findings"))
	}

	if len(pr.TestSelections) > 0 {
		if len(pr.TestSelections) <= 5 {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			line("  - Run %d %s: %s", len(paths), pluralize(len(paths), "test", "tests"), strings.Join(paths, ", "))
		} else {
			line("  - Run %d %s (see full comment for details)", len(pr.TestSelections), pluralize(len(pr.TestSelections), "test", "tests"))
		}
	}
}

// RenderCIAnnotation writes CI-annotation-style output.
func RenderCIAnnotation(w io.Writer, pr *PRAnalysis) {
	findings := DeduplicateFindings(pr.NewFindings)
	for _, f := range findings {
		level := "notice"
		switch f.Severity {
		case "high":
			level = "error"
		case "medium":
			level = "warning"
		}
		fmt.Fprintf(w, "::%s file=%s::%s\n", level, f.Path, f.Explanation)
	}
}

// RenderChangeScopedReport writes a human-readable change-scoped report.
func RenderChangeScopedReport(w io.Writer, pr *PRAnalysis) {
	line := func(format string, args ...any) {
		fmt.Fprintf(w, format+"\n", args...)
	}
	blank := func() { fmt.Fprintln(w) }

	findings := DeduplicateFindings(pr.NewFindings)
	mergeRec, mergeExpl := MergeRecommendation(pr.PostureBand, findings)

	line("Terrain — Change-Scoped Analysis")
	line(strings.Repeat("=", 40))
	blank()

	line("Recommendation:  %s", mergeRec)
	line("Posture:         %s", strings.ToUpper(pr.PostureBand))
	line("Files:           %d changed (%d source, %d test)", pr.ChangedFileCount, pr.ChangedSourceCount, pr.ChangedTestCount)
	line("Units:           %d impacted", pr.ImpactedUnitCount)
	line("Gaps:            %d", pr.ProtectionGapCount)
	if len(pr.RecommendedTests) > 0 && pr.TotalTestCount > 0 {
		line("Tests:           %d of %d (%.0f%% reduction)", len(pr.RecommendedTests), pr.TotalTestCount,
			100.0-100.0*float64(len(pr.RecommendedTests))/float64(pr.TotalTestCount))
	}
	line("Reason:          %s", mergeExpl)
	blank()

	directRisk, indirectRisk, existingDebt := ClassifyFindingsDetailed(findings)

	if len(directRisk) > 0 {
		line("New Risks (directly changed)")
		line(strings.Repeat("-", 40))
		renderFindingsByPath(line, directRisk)
		blank()
	}

	if len(indirectRisk) > 0 {
		line("Indirectly Impacted Gaps (%d)", len(indirectRisk))
		line(strings.Repeat("-", 40))
		renderFindingsByPath(line, indirectRisk)
		blank()
	}

	if len(existingDebt) > 0 {
		line("Pre-Existing Issues")
		line(strings.Repeat("-", 40))
		renderFindingsByPath(line, existingDebt)
		blank()
	}

	if len(pr.TestSelections) > 0 {
		line("Recommended Tests (%d)", len(pr.TestSelections))
		line(strings.Repeat("-", 40))
		if pr.SelectionExplanation != "" {
			line("  Strategy: %s", pr.SelectionExplanation)
			blank()
		}
		if len(pr.TestSelections) <= 20 {
			reasons := formatTestReasons(pr.TestSelections)
			for _, t := range pr.TestSelections {
				line("  [%s] %s", t.Confidence, t.Path)
				line("         %s", reasons[t.Path])
			}
		} else {
			paths := make([]string, len(pr.TestSelections))
			for i, t := range pr.TestSelections {
				paths[i] = t.Path
			}
			for _, g := range GroupTestsByPackage(paths) {
				line("  %s/ — %d %s", g.Package, g.Count, pluralize(g.Count, "test", "tests"))
			}
		}
		blank()
	}

	if len(pr.AffectedOwners) > 0 {
		line("Affected Owners: %s", strings.Join(pr.AffectedOwners, ", "))
		blank()
	}

	// AI risk review summary.
	if ai := pr.AI; ai != nil {
		line("AI Risk Review")
		line(strings.Repeat("-", 40))
		line("  Scenarios: %d of %d selected", ai.SelectedScenarios, ai.TotalScenarios)
		if len(ai.ImpactedCapabilities) > 0 {
			line("  Capabilities: %s", strings.Join(ai.ImpactedCapabilities, ", "))
		}
		if len(ai.BlockingSignals) > 0 {
			groups := groupSignalsByFileAndType(ai.BlockingSignals)
			line("  %d new %s on changed files:", len(groups), pluralize(len(groups), "finding", "findings"))
			for _, g := range groups {
				summary := humanSummary[g.Type]
				if summary == "" {
					summary = g.Explanation
				}
				loc := g.File
				switch {
				case len(g.Lines) > 0:
					strs := make([]string, len(g.Lines))
					for i, ln := range g.Lines {
						strs[i] = fmt.Sprintf("%d", ln)
					}
					loc = fmt.Sprintf("%s:%s", g.File, strings.Join(strs, ","))
				case len(g.Symbols) > 0:
					loc = fmt.Sprintf("%s (%s)", g.File, strings.Join(g.Symbols, ", "))
				}
				line("    %s %s — %s", uitokens.BracketedSeverity(g.Severity), loc, summary)
				if action := humanAction[g.Type]; action != "" {
					line("      → %s", action)
				}
			}
		}
		if len(ai.UncoveredContexts) > 0 {
			line("  Uncovered AI surfaces: %d", len(ai.UncoveredContexts))
			for _, c := range ai.UncoveredContexts {
				line("    - %s", c)
			}
		}
		blank()
	}

	// Drop full-repo edge-case advisories from the PR view; they
	// confuse adopters when they appear under a diff-scoped report.
	if filtered := filterDiffScopedLimitations(pr.Limitations); len(filtered) > 0 {
		line("Limitations")
		line(strings.Repeat("-", 40))
		for _, l := range filtered {
			line("  %s", l)
		}
		blank()
	}
}

// collapseLinebreaks joins multi-line strings into one line so that
// detector explanations with hard-wrap source formatting don't break
// markdown list items on the PR-comment surface. Single-line input
// returns unchanged; multi-line input collapses to a single
// space-separated line.
func collapseLinebreaks(s string) string {
	if !strings.Contains(s, "\n") {
		return s
	}
	var b strings.Builder
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		if b.Len() > 0 {
			b.WriteString(" ")
		}
		b.WriteString(trimmed)
	}
	return b.String()
}

// stripSignalTypePrefix removes a leading `[signalType]` token from
// an explanation string. Some detectors emit `[fooBar] explanation
// text`; the same id is already in the hidden `terrain:finding=`
// marker, so duplicating it inline is just noise.
func stripSignalTypePrefix(s, signalType string) string {
	if signalType == "" {
		return s
	}
	prefix := "[" + signalType + "] "
	return strings.TrimPrefix(s, prefix)
}

// filterDiffScopedLimitations strips full-repo advisories ("too few
// tests", "CI is already fast", etc.) from the PR-scoped limitations
// list. Mirrors internal/reporting.filterDiffScopedLimitations —
// duplicated here to keep changescope independent of reporting in
// the package graph.
func filterDiffScopedLimitations(lims []string) []string {
	if len(lims) == 0 {
		return nil
	}
	dropPrefixes := []string{
		"too few tests",
		"ci is already fast",
		"ci is fast",
		"high test duplication",
		"high proportion of skipped",
		"high proportion of flaky",
		"low graph visibility",
	}
	out := make([]string, 0, len(lims))
	for _, lim := range lims {
		lower := strings.ToLower(strings.TrimLeft(lim, " *•"))
		drop := false
		for _, p := range dropPrefixes {
			if strings.HasPrefix(lower, p) {
				drop = true
				break
			}
		}
		if !drop {
			out = append(out, lim)
		}
	}
	return out
}

// renderAISection renders the AI risk review summary in markdown.
func renderAISection(line func(string, ...any), pr *PRAnalysis) {
	ai := pr.AI
	if ai == nil {
		return
	}

	line("### AI Risk Review")
	line("")

	// Compact context line: capabilities + scenarios in one row.
	// Pre-fix this was two separate stanzas (a bold-label inline label
	// and a plain "Scenarios: X of Y selected" line). One blockquote
	// reads more cleanly and renders as a callout on GitHub.
	contextParts := []string{}
	if len(ai.ImpactedCapabilities) > 0 {
		contextParts = append(contextParts,
			fmt.Sprintf("**Capabilities:** %s", strings.Join(ai.ImpactedCapabilities, ", ")))
	}
	contextParts = append(contextParts,
		fmt.Sprintf("**Scenarios:** %d of %d selected", ai.SelectedScenarios, ai.TotalScenarios))
	line("> %s", strings.Join(contextParts, " · "))
	line("")

	// Blocking signals — grouped by (file, type) so 12 prompt-injection
	// hits across 4 files become 4 bullets, not 12. Each bullet leads
	// with the file:line locator and a plain-language summary instead
	// of detector taxonomy. See ai_signal_humanize.go.
	if len(ai.BlockingSignals) > 0 {
		groups := groupSignalsByFileAndType(ai.BlockingSignals)
		line("**%d new %s introduced by this PR:**", len(groups), pluralize(len(groups), "finding", "findings"))
		line("")
		for _, g := range groups {
			for _, l := range renderGroupedSignal(g) {
				line("%s", l)
			}
		}
		line("")
	}

	// Warning signals follow the same grouping. Wrapped in a details
	// element so they're collapsed by default in GitHub.
	if len(ai.WarningSignals) > 0 {
		groups := groupSignalsByFileAndType(ai.WarningSignals)
		line("<details><summary><b>%d advisory %s</b></summary>", len(groups), pluralize(len(groups), "finding", "findings"))
		line("")
		for _, g := range groups {
			for _, l := range renderGroupedSignal(g) {
				line("%s", l)
			}
		}
		line("")
		line("</details>")
		line("")
	}

	// Impacted scenarios grouped by capability.
	if len(ai.Scenarios) > 0 {
		// Group by capability.
		byCap := map[string][]EvalSummary{}
		var noCap []EvalSummary
		for _, sc := range ai.Scenarios {
			if sc.Capability != "" {
				byCap[sc.Capability] = append(byCap[sc.Capability], sc)
			} else {
				noCap = append(noCap, sc)
			}
		}

		if len(byCap) > 0 || len(noCap) > 0 {
			line("<details><summary>Impacted scenarios (%d)</summary>", len(ai.Scenarios))
			line("")
			// Sort capability keys.
			caps := make([]string, 0, len(byCap))
			for c := range byCap {
				caps = append(caps, c)
			}
			sort.Strings(caps)
			for _, cap := range caps {
				line("**%s:**", cap)
				for _, sc := range byCap[cap] {
					line("- %s — %s", sc.Name, sc.Reason)
				}
			}
			if len(noCap) > 0 {
				for _, sc := range noCap {
					line("- %s — %s", sc.Name, sc.Reason)
				}
			}
			line("")
			line("</details>")
			line("")
		}
	}

	// Uncovered AI surfaces.
	if len(ai.UncoveredContexts) > 0 {
		line("**Changed AI surfaces without eval coverage (%d):**", len(ai.UncoveredContexts))
		line("")
		for _, c := range ai.UncoveredContexts {
			line("- `%s`", c)
		}
		line("")
	}
}

// postureBadge delegates to uitokens.BracketedVerdict so the badge
// vocabulary is owned by the design system.
func postureBadge(band string) string {
	return uitokens.BracketedVerdict(band)
}

// severityIcon delegates to uitokens.BracketedSeverity so the badge
// vocabulary is owned by the design system. Every renderer that
// emits user-visible severity should consume from uitokens rather
// than carrying its own switch. The wrapper is kept (rather than
// inlining the call) so internal helpers like
// renderFindingCard remain unchanged and the diff stays surgical.
func severityIcon(severity string) string {
	return uitokens.BracketedSeverity(severity)
}

// formatSuitePercent renders selected/total as a percentage with
// honest precision for small fractions. Pre-fix the integer-division
// formula floored 7-of-796 to "0% of suite" — adopters seeing
// "0%" reasonably wonder whether selection ran at all. Now sub-1%
// fractions render as "<1%", and values ≥1% render as integer
// percentages.
func formatSuitePercent(selected, total int) string {
	if total <= 0 {
		return "—"
	}
	if selected <= 0 {
		return "0%"
	}
	pct := 100 * selected / total
	if pct == 0 {
		return "<1%"
	}
	return fmt.Sprintf("%d%%", pct)
}

func formatSeverityCounts(counts map[string]int) []string {
	var parts []string
	for _, sev := range []string{"high", "medium", "low"} {
		if c, ok := counts[sev]; ok && c > 0 {
			parts = append(parts, fmt.Sprintf("%d %s", c, sev))
		}
	}
	return parts
}

func deduplicateReasons(reasons []string) string {
	seen := map[string]int{}
	var unique []string
	for _, r := range reasons {
		seen[r]++
		if seen[r] == 1 {
			unique = append(unique, r)
		}
	}
	var parts []string
	for _, r := range unique {
		if seen[r] > 1 {
			parts = append(parts, fmt.Sprintf("%s (%dx)", r, seen[r]))
		} else {
			parts = append(parts, r)
		}
	}
	return strings.Join(parts, "; ")
}

func formatTestReasons(selections []TestSelection) map[string]string {
	reasons := map[string]string{}
	unitTestCount := map[string]int{}
	for _, t := range selections {
		for _, uid := range t.CoversUnits {
			unitTestCount[uid]++
		}
	}
	totalTests := len(selections)
	for _, t := range selections {
		reasons[t.Path] = formatSingleTestReason(t, unitTestCount, totalTests)
	}
	return reasons
}

func formatSingleTestReason(t TestSelection, unitTestCount map[string]int, totalTests int) string {
	unitNames := extractUnitNames(t.CoversUnits)
	if len(unitNames) == 0 {
		if len(t.Reasons) > 0 {
			return deduplicateReasons(t.Reasons)
		}
		return t.Relevance
	}
	var unique, shared []string
	for _, uid := range t.CoversUnits {
		name := uid
		if idx := strings.LastIndex(uid, ":"); idx >= 0 {
			name = uid[idx+1:]
		}
		if unitTestCount[uid] == 1 {
			unique = append(unique, name)
		} else {
			shared = append(shared, name)
		}
	}
	unique = deduplicateStrings(unique)
	shared = deduplicateStrings(shared)
	label := "covers"
	if t.Confidence == "exact" {
		label = "exact coverage of"
	}
	const maxDisplay = 3
	if len(unique) > 0 {
		var why string
		if len(unique) <= maxDisplay {
			why = fmt.Sprintf("%s %s", label, formatUnitList(unique))
		} else {
			why = fmt.Sprintf("%s %s + %d more", label, formatUnitList(unique[:maxDisplay]), len(unique)-maxDisplay)
		}
		return why
	}
	if len(unitNames) <= maxDisplay {
		return fmt.Sprintf("%s %s", label, formatUnitList(unitNames))
	}
	return fmt.Sprintf("%s %s + %d more", label, formatUnitList(unitNames[:maxDisplay]), len(unitNames)-maxDisplay)
}

// formatUnitList renders unit names as a comma-separated inline code list.
func formatUnitList(names []string) string {
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "`" + n + "`"
	}
	return strings.Join(parts, ", ")
}

func deduplicateStrings(ss []string) []string {
	seen := map[string]bool{}
	var out []string
	for _, s := range ss {
		if !seen[s] {
			seen[s] = true
			out = append(out, s)
		}
	}
	return out
}

func extractUnitNames(unitIDs []string) []string {
	if len(unitIDs) == 0 {
		return nil
	}
	seen := map[string]bool{}
	var names []string
	for _, id := range unitIDs {
		name := id
		if idx := strings.LastIndex(id, ":"); idx >= 0 {
			name = id[idx+1:]
		}
		if name != "" && !seen[name] {
			seen[name] = true
			names = append(names, name)
		}
	}
	return names
}

// isEmptyPR reports whether a PR has nothing substantive to flag —
// no new findings, no AI risk section, no protection gaps. Used by
// the markdown renderer to emit a designed "all clear" callout
// instead of an awkwardly-thin comment that reads as broken.
func isEmptyPR(pr *PRAnalysis) bool {
	if pr == nil {
		return false
	}
	if len(pr.NewFindings) > 0 {
		return false
	}
	if pr.ProtectionGapCount > 0 {
		return false
	}
	if pr.AI != nil && (len(pr.AI.BlockingSignals) > 0 || len(pr.AI.UncoveredContexts) > 0) {
		return false
	}
	return true
}

// buildConfidenceHistogram renders a one-line summary of how the
// recommended test set distributes by confidence. Returns "" when
// the set is small enough that the table itself shows the same
// information clearly.
//
// Format example:
//
//	**Confidence:** 12 exact · 4 inferred · 1 weak (17 tests selected)
//
// Provides observability into how the test set was assembled,
// not just which tests were chosen.
func buildConfidenceHistogram(selections []TestSelection) string {
	if len(selections) == 0 {
		return ""
	}
	counts := map[string]int{}
	order := []string{} // first-seen order for stability
	for _, t := range selections {
		c := t.Confidence
		if c == "" {
			c = "unknown"
		}
		if _, exists := counts[c]; !exists {
			order = append(order, c)
		}
		counts[c]++
	}
	parts := make([]string, 0, len(order))
	for _, c := range order {
		parts = append(parts, fmt.Sprintf("%d %s", counts[c], c))
	}
	return fmt.Sprintf("**Confidence:** %s (%d %s selected)",
		strings.Join(parts, " · "),
		len(selections),
		pluralize(len(selections), "test", "tests"),
	)
}
