package aipipeline

import "math"

// Posture distinguishes Observability (PR comment / report only) from
// Gate (`--fail-on=high` blocks CI). Same engine; different thresholds
// and stricter fallback handling in Gate.
type Posture string

const (
	PostureObservability Posture = "observability"
	PostureGate          Posture = "gate"
)

// Finding is the composed result for a single (path, rule) candidate.
// The composer assembles findings from a Candidate's atoms.
type Finding struct {
	Path       string
	RuleID     string
	Cohort     string
	Confidence float64 // 0.0–1.0, post-sigmoid
	LogOdds    float64 // pre-sigmoid sum
	Severity   Severity
	Atoms      []EvidenceAtom
	Fallbacks  []string

	// FixScaffold is an optional remediation snippet generated by the
	// fixscaffold package. Empty when the rule has no scaffold producer.
	FixScaffold string

	// Suppressed reports whether posture-specific gates rejected the
	// finding (e.g. uncalibrated finding in Gate mode). Useful for
	// surfacing "would-fire-in-other-mode" diagnostics.
	Suppressed       bool
	SuppressedReason string
}

// Severity is the rendered severity tier for a finding. Derived from
// the rule manifest and modulated by confidence + posture.
type Severity string

const (
	SeverityLow      Severity = "low"
	SeverityMedium   Severity = "medium"
	SeverityHigh     Severity = "high"
	SeverityCritical Severity = "critical"
)

// ScaffoldGenerator returns a fix-scaffold body and target path for a
// given (rule, surface, language). Returns the empty string when no
// scaffold is appropriate. The concrete generator registry lives in
// internal/aipipeline/fixscaffold; this interface is the seam.
type ScaffoldGenerator interface {
	GenerateScaffold(ruleID, surfacePath, lang string) (body, target, description string)
}

// Composer turns a Candidate's accumulated atoms into a Finding. The
// composer is the only consumer of the calibration table; stages
// produce atoms with default weights and the composer may override.
type Composer struct {
	Calibration *Calibration
	Posture     Posture

	// Scaffolds, when set, generates a fix-scaffold for emitted
	// findings. Optional; nil leaves Finding.FixScaffold empty.
	Scaffolds ScaffoldGenerator
}

// NewComposer constructs a Composer with sensible defaults. Calibration
// may be nil — the composer falls back to atom default weights.
func NewComposer(cal *Calibration, posture Posture) *Composer {
	if posture == "" {
		posture = PostureObservability
	}
	return &Composer{
		Calibration: cal,
		Posture:     posture,
	}
}

// Compose computes the final Finding from a candidate's atoms. The
// math is:
//
//	logOdds = base_rate(cohort, rule) + Σ weight_i
//	confidence = sigmoid(logOdds)
//
// Weight_i comes from the calibration table when present; otherwise
// the atom's default Weight is used. Negative atoms reduce the score.
//
// Posture gates (uncalibrated, ast-unavailable, etc.) may set
// Suppressed=true on the result.
func (c *Composer) Compose(cand *Candidate) Finding {
	rule := cand.RuleID
	cohort := cand.Cohort
	if cohort == "" {
		cohort = "unknown"
	}

	base := 0.0
	if c.Calibration != nil {
		base = c.Calibration.BaseRate(cohort, rule)
	}

	sum := base
	for _, a := range cand.Atoms {
		w := a.Weight
		if c.Calibration != nil {
			if override, ok := c.Calibration.AtomWeight(cohort, rule, a.RuleID); ok {
				w = override
			}
		}
		sum += w
	}

	conf := sigmoid(sum)
	sev := c.severityFor(rule, conf)

	finding := Finding{
		Path:       cand.Path,
		RuleID:     rule,
		Cohort:     cand.Cohort,
		Confidence: conf,
		LogOdds:    sum,
		Severity:   sev,
		Atoms:      cand.Atoms,
		Fallbacks:  cand.Fallbacks,
	}

	c.applyPostureGates(&finding)
	c.attachScaffold(cand, &finding)

	return finding
}

func (c *Composer) attachScaffold(cand *Candidate, f *Finding) {
	if c.Scaffolds == nil {
		return
	}
	body, _, _ := c.Scaffolds.GenerateScaffold(cand.RuleID, cand.Path, cand.Lang)
	if body == "" {
		return
	}
	f.FixScaffold = body
}

// ThresholdFor returns the posture-specific confidence threshold below
// which a finding is suppressed from output.
func (c *Composer) ThresholdFor(rule string) float64 {
	if c.Calibration != nil {
		if t, ok := c.Calibration.Threshold(c.Posture, rule); ok {
			return t
		}
	}
	switch c.Posture {
	case PostureGate:
		return 0.80
	default:
		return 0.40
	}
}

// ShouldEmit reports whether a finding meets the posture threshold for
// surfacing to the user.
func (c *Composer) ShouldEmit(f Finding) bool {
	if f.Suppressed {
		return false
	}
	return f.Confidence >= c.ThresholdFor(f.RuleID)
}

func (c *Composer) severityFor(rule string, conf float64) Severity {
	// Until manifest plumbing lands here, derive severity from confidence
	// bands. Calibrated rules should override via Calibration.SeverityFor.
	if c.Calibration != nil {
		if s, ok := c.Calibration.SeverityFor(rule); ok {
			return adjustSeverity(s, conf)
		}
	}
	switch {
	case conf >= 0.90:
		return SeverityHigh
	case conf >= 0.70:
		return SeverityMedium
	default:
		return SeverityLow
	}
}

func (c *Composer) applyPostureGates(f *Finding) {
	if c.Posture != PostureGate {
		return
	}
	// In Gate posture, AST-unavailable and uncalibrated findings are
	// suppressed (the observability tier still emits them with markers).
	for _, fb := range f.Fallbacks {
		if fb == "ast=unavailable" {
			f.Suppressed = true
			f.SuppressedReason = "ast=unavailable (gate posture requires structural confirmation)"
			return
		}
		if fb == "uncalibrated" {
			f.Suppressed = true
			f.SuppressedReason = "rule lacks calibration entry"
			return
		}
	}
}

// adjustSeverity nudges severity within one band based on confidence.
// A "high" rule at 0.45 confidence drops to medium; a "low" rule at
// 0.95 confidence rises to medium.
func adjustSeverity(declared Severity, conf float64) Severity {
	switch declared {
	case SeverityCritical:
		if conf < 0.50 {
			return SeverityHigh
		}
		return declared
	case SeverityHigh:
		if conf < 0.50 {
			return SeverityMedium
		}
		return declared
	case SeverityMedium:
		if conf < 0.40 {
			return SeverityLow
		}
		if conf >= 0.90 {
			return SeverityHigh
		}
		return declared
	case SeverityLow:
		if conf >= 0.90 {
			return SeverityMedium
		}
		return declared
	}
	return declared
}

// sigmoid maps log-odds to a probability-style confidence in [0, 1].
func sigmoid(x float64) float64 {
	if x >= 0 {
		return 1.0 / (1.0 + math.Exp(-x))
	}
	ex := math.Exp(x)
	return ex / (1.0 + ex)
}
