package scaffold

import (
	"encoding/json"
	"fmt"
	"strings"
)

// EmitOptions controls scaffold rendering.
type EmitOptions struct {
	// SchemaPath identifies the schema (printed as a header comment).
	SchemaPath string
	// PromptPath identifies the prompt under test (printed in the
	// header so the test author knows which call site to wire).
	PromptPath string
	// Language selects the scaffold flavor: "python", "typescript",
	// or "json".
	Language string
}

// Emit renders the boundary cases as a runnable test scaffold or a
// raw JSON dump. The output goes to the adopter's tests directory.
func Emit(cases []BoundaryCase, opts EmitOptions) string {
	switch opts.Language {
	case "typescript", "ts":
		return emitTypeScript(cases, opts)
	case "json":
		return emitJSON(cases, opts)
	default:
		return emitPython(cases, opts)
	}
}

func emitPython(cases []BoundaryCase, opts EmitOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by `terrain scaffold`. Drop into your tests/ tree.\n")
	if opts.SchemaPath != "" {
		fmt.Fprintf(&b, "# Schema: %s\n", opts.SchemaPath)
	}
	if opts.PromptPath != "" {
		fmt.Fprintf(&b, "# Prompt under test: %s\n", opts.PromptPath)
	}
	fmt.Fprintf(&b, "#\n")
	fmt.Fprintf(&b, "# Replace `your_prompt_invoke(...)` with the call into your\n")
	fmt.Fprintf(&b, "# prompt pipeline. Each test exercises one boundary case\n")
	fmt.Fprintf(&b, "# generated from the schema's declared types.\n\n")
	fmt.Fprintf(&b, "import pytest\n\n")
	byField := groupByField(cases)
	seen := map[string]int{}
	for _, field := range sortedFields(byField) {
		fieldCases := byField[field]
		safeName := safePythonIdent(field)
		if n := seen[safeName]; n > 0 {
			seen[safeName] = n + 1
			safeName = fmt.Sprintf("%s_%d", safeName, n+1)
		} else {
			seen[safeName] = 1
		}
		fmt.Fprintf(&b, "@pytest.mark.parametrize(\"value, why\", [\n")
		for _, c := range fieldCases {
			fmt.Fprintf(&b, "    (%s, %q),\n", pythonRepr(c.Value), c.Why)
		}
		fmt.Fprintf(&b, "])\n")
		fmt.Fprintf(&b, "def test_boundary_%s(value, why):\n", safeName)
		fmt.Fprintf(&b, "    payload = {%q: value}\n", field)
		fmt.Fprintf(&b, "    result = your_prompt_invoke(payload)\n")
		fmt.Fprintf(&b, "    # Assert the prompt rejects the input cleanly or\n")
		fmt.Fprintf(&b, "    # produces a safe degradation. Boundary class is in `why`.\n")
		fmt.Fprintf(&b, "    assert handles_boundary(result, value), (\n")
		fmt.Fprintf(&b, "        f\"field '%s' mishandled boundary case ({why!r}): {value!r}\"\n", field)
		fmt.Fprintf(&b, "    )\n\n")
	}
	return b.String()
}

func emitTypeScript(cases []BoundaryCase, opts EmitOptions) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// Generated by `terrain scaffold`. Drop into your tests/ tree.\n")
	if opts.SchemaPath != "" {
		fmt.Fprintf(&b, "// Schema: %s\n", opts.SchemaPath)
	}
	if opts.PromptPath != "" {
		fmt.Fprintf(&b, "// Prompt under test: %s\n", opts.PromptPath)
	}
	fmt.Fprintf(&b, "//\n")
	fmt.Fprintf(&b, "// Replace `yourPromptInvoke(...)` with the call into your\n")
	fmt.Fprintf(&b, "// prompt pipeline. Each describe block exercises one schema\n")
	fmt.Fprintf(&b, "// field's boundary cases.\n\n")
	fmt.Fprintf(&b, "import { describe, it, expect } from 'vitest';\n\n")
	byField := groupByField(cases)
	for _, field := range sortedFields(byField) {
		fieldCases := byField[field]
		fmt.Fprintf(&b, "describe(%q, () => {\n", "boundary cases — "+field)
		fmt.Fprintf(&b, "  const cases: { value: unknown; why: string }[] = [\n")
		for _, c := range fieldCases {
			fmt.Fprintf(&b, "    { value: %s, why: %q },\n", tsRepr(c.Value), c.Why)
		}
		fmt.Fprintf(&b, "  ];\n")
		fmt.Fprintf(&b, "  it.each(cases)('handles $why', async ({ value, why }) => {\n")
		fmt.Fprintf(&b, "    const payload = { %q: value };\n", field)
		fmt.Fprintf(&b, "    const result = await yourPromptInvoke(payload);\n")
		fmt.Fprintf(&b, "    expect(handlesBoundary(result, value)).toBe(true);\n")
		fmt.Fprintf(&b, "  });\n")
		fmt.Fprintf(&b, "});\n\n")
	}
	return b.String()
}

func emitJSON(cases []BoundaryCase, _ EmitOptions) string {
	type out struct {
		Cases []BoundaryCase `json:"cases"`
	}
	body, _ := json.MarshalIndent(out{Cases: cases}, "", "  ")
	return string(body) + "\n"
}

func groupByField(cases []BoundaryCase) map[string][]BoundaryCase {
	out := map[string][]BoundaryCase{}
	for _, c := range cases {
		out[c.Field] = append(out[c.Field], c)
	}
	return out
}

func sortedFields(m map[string][]BoundaryCase) []string {
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	// Stable sort.
	for i := 1; i < len(names); i++ {
		for j := i; j > 0 && names[j] < names[j-1]; j-- {
			names[j], names[j-1] = names[j-1], names[j]
		}
	}
	return names
}

// safePythonIdent converts a field name to a Python-safe identifier
// (snake_case, leading-letter, no special chars).
func safePythonIdent(s string) string {
	var b strings.Builder
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteByte('_')
			}
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r - 'A' + 'a')
		default:
			b.WriteByte('_')
		}
	}
	if b.Len() == 0 {
		return "field"
	}
	return b.String()
}

func pythonRepr(v any) string {
	body, _ := json.Marshal(v)
	s := string(body)
	// JSON true/false/null → Python True/False/None.
	switch s {
	case "true":
		return "True"
	case "false":
		return "False"
	case "null":
		return "None"
	}
	return s
}

func tsRepr(v any) string {
	body, _ := json.Marshal(v)
	return string(body)
}
